import { eq } from "drizzle-orm";
import { ensureCoreTables, getDb } from "../../../db";
import { auditEvents, entities, hrAccesses, hrCandidates, hrInterviews, hrRewards, hrEmployees, tasks } from "../../../db/schema";
import { nextCandidateStage } from "../../../lib/hr";
import { getAuthenticatedRequestContext } from "../../../lib/production-auth";
import { isTaskManager, resolveTaskAssignment, type TaskAccessContext } from "../../../lib/task-access";
import { findScopedAutomationTask, scopedAutomationTaskResponse } from "../../../lib/task-access-query";

const editors=new Set(["OWNER","DIRECTOR","REPRESENTATIVE","HR"]);
export async function POST(request:Request){let context;try{context=await getAuthenticatedRequestContext(request)}catch{return Response.json({error:"Сервис авторизации временно недоступен"},{status:503})}if(!context)return Response.json({error:"Требуется вход"},{status:401});const actor=context.actor;if(!editors.has(context.apiRole))return Response.json({error:"Нет прав на HR-действие"},{status:403});try{await ensureCoreTables();const body=await request.json() as Record<string,unknown>,action=clean(body.action,50);if(action==="createEmployee")return createEmployee(actor,body);if(action==="updateEmployee")return updateEmployee(actor,body);if(action==="importEmployees")return importEmployees(actor,body);if(action==="advanceCandidate")return advance(actor,body);if(action==="recordInterview")return interview(actor,body);if(action==="createOnboardingTask")return onboarding(context,body);if(action==="recordPersonnelEvent")return personnelEvent(actor,body);if(action==="terminateEmployee")return terminate(actor,body);return Response.json({error:"Неизвестное действие"},{status:400})}catch(error){return Response.json({error:error instanceof Error?error.message:"Действие не выполнено"},{status:500})}}

async function createEmployee(actor:string,body:Record<string,unknown>){
  const values=employeeValues(body);if("error" in values)return Response.json({error:values.error},{status:400});
  const db=getDb(),id=`EMP-M-${crypto.randomUUID().slice(0,8).toUpperCase()}`,now=new Date().toISOString();
  const [duplicate]=await db.select().from(entities).where(eq(entities.displayName,values.displayName)).limit(1);
  if(duplicate&&duplicate.entityType==="Сотрудник"&&duplicate.status!=="Объединена")return Response.json({error:`Возможный дубль: ${duplicate.displayName} · ${duplicate.id}`},{status:409});
  await db.insert(entities).values({id,entityType:"Сотрудник",displayName:values.displayName,status:employeeEntityStatus(values.status),sourceSystem:"MANUAL",sourceRecordId:`MANUAL:${id}`,dataQuality:"Проверено",scope:values.unit,metadata:JSON.stringify({contact:values.contact,position:values.positionId,employmentType:values.employmentType,branch:values.unit,branches:values.branchNames,branchIds:values.branchIds,note:values.note}),createdBy:actor,updatedAt:now});
  const [employee]=await db.insert(hrEmployees).values({id,candidateId:"",contractId:values.contractId,positionId:values.positionId,unit:values.unit,rateMinor:values.rateMinor,hireDate:values.hireDate,status:values.status,accessStatus:"Доступ не выдан",updatedAt:now}).returning();
  await audit(actor,"hr.employee_created","entity",id,{source:"MANUAL",provenance:"Создано вручную",dataQuality:"Проверено",operationalStatus:employeeEntityStatus(values.status),access:"not_granted",unit:values.unit,positionId:values.positionId});
  return Response.json({employee},{status:201});
}

async function updateEmployee(actor:string,body:Record<string,unknown>){
  const id=clean(body.employeeId,80),values=employeeValues(body);if(!id)return Response.json({error:"Сотрудник не выбран"},{status:400});if("error" in values)return Response.json({error:values.error},{status:400});
  const db=getDb(),[current]=await db.select().from(hrEmployees).where(eq(hrEmployees.id,id)).limit(1);if(!current)return Response.json({error:"Сотрудник не найден"},{status:404});
  const now=new Date().toISOString();
  const [employee]=await db.update(hrEmployees).set({contractId:values.contractId,positionId:values.positionId,unit:values.unit,rateMinor:values.rateMinor,hireDate:values.hireDate,status:values.status,updatedAt:now}).where(eq(hrEmployees.id,id)).returning();
  await db.update(entities).set({displayName:values.displayName,status:employeeEntityStatus(values.status),scope:values.unit,metadata:JSON.stringify({contact:values.contact,position:values.positionId,employmentType:values.employmentType,branch:values.unit,branches:values.branchNames,branchIds:values.branchIds,note:values.note}),updatedAt:now}).where(eq(entities.id,id));
  await audit(actor,"hr.employee_updated","entity",id,{unit:values.unit,positionId:values.positionId,status:values.status});
  return Response.json({employee});
}

async function importEmployees(actor:string,body:Record<string,unknown>){
  const rows=Array.isArray(body.rows)?body.rows.slice(0,100):[];if(!rows.length)return Response.json({error:"В файле нет строк для импорта"},{status:400});
  const db=getDb(),created:string[]=[],rejected:Array<{row:number;reason:string}>=[];
  for(let index=0;index<rows.length;index+=1){
    const raw=(rows[index]&&typeof rows[index]==="object"?rows[index]:{}) as Record<string,unknown>,values=employeeValues(raw);
    if("error" in values){rejected.push({row:index+1,reason:values.error ?? "Строка не прошла проверку"});continue}
    const [duplicate]=await db.select().from(entities).where(eq(entities.displayName,values.displayName)).limit(1);if(duplicate&&duplicate.entityType==="Сотрудник"&&duplicate.status!=="Объединена"){rejected.push({row:index+1,reason:`возможный дубль ${duplicate.id}`});continue}
    const id=`EMP-I-${crypto.randomUUID().slice(0,8).toUpperCase()}`,now=new Date().toISOString();
    await db.insert(entities).values({id,entityType:"Сотрудник",displayName:values.displayName,status:"На проверке",sourceSystem:"CSV_IMPORT",sourceRecordId:`CSV:${id}`,dataQuality:"На проверке",scope:values.unit,metadata:JSON.stringify({contact:values.contact,position:values.positionId,employmentType:values.employmentType,branch:values.unit,branches:values.branchNames,branchIds:values.branchIds,note:values.note}),createdBy:actor,updatedAt:now});
    await db.insert(hrEmployees).values({id,candidateId:"",contractId:values.contractId,positionId:values.positionId,unit:values.unit,rateMinor:values.rateMinor,hireDate:values.hireDate,status:values.status,accessStatus:"Доступ не выдан",updatedAt:now});
    await audit(actor,"hr.employee_imported","entity",id,{source:"CSV_IMPORT",row:index+1,access:"not_granted"});created.push(id);
  }
  return Response.json({created:created.length,rejected},{status:created.length?201:409});
}

async function advance(actor:string,body:Record<string,unknown>){const id=clean(body.candidateId,80),target=clean(body.targetStage,30),evidence=clean(body.evidence,500),db=getDb();const[row]=await db.select().from(hrCandidates).where(eq(hrCandidates.id,id)).limit(1);if(!row)return Response.json({error:"Кандидат не найден"},{status:404});if(!nextCandidateStage(row.stage,target)||evidence.length<8)return Response.json({error:"Допустим только следующий этап с доказательством"},{status:409});const[updated]=await db.update(hrCandidates).set({stage:target,evidence,updatedAt:new Date().toISOString()}).where(eq(hrCandidates.id,id)).returning();await audit(actor,"hr.candidate_advanced","hr_candidate",id,{from:row.stage,to:target,evidence});return Response.json({candidate:updated})}
async function interview(actor:string,body:Record<string,unknown>){const candidateId=clean(body.candidateId,80),summary=clean(body.summary,600),decision=clean(body.decision,100),score=Number(body.score),requestedInterviewer=clean(body.interviewerEntityId,80);if(summary.length<10||!decision||!Number.isInteger(score)||score<0||score>100)return Response.json({error:"Нужны оценка 0–100, решение и итог интервью"},{status:400});const db=getDb();const[candidate]=await db.select().from(hrCandidates).where(eq(hrCandidates.id,candidateId)).limit(1);if(!candidate)return Response.json({error:"Кандидат не найден"},{status:404});const interviewerEntityId=await verifiedEntityId(requestedInterviewer);if(requestedInterviewer&&!interviewerEntityId)return Response.json({error:"Интервьюер не найден"},{status:400});const id=`INTV-${crypto.randomUUID().slice(0,8).toUpperCase()}`;const[row]=await db.insert(hrInterviews).values({id,candidateId,scheduledAt:new Date().toISOString(),interviewerEntityId,score,summary,decision}).returning();await audit(actor,"hr.interview_recorded","hr_interview",id,{candidateId,score,decision,recordedBy:actor,interviewerEntityId});return Response.json({interview:row},{status:201})}
async function onboarding(context:TaskAccessContext,body:Record<string,unknown>){const actor=context.actor,employeeId=clean(body.employeeId,80),requestedAssignee=clean(body.assigneeEntityId,80),db=getDb(),key=`HR_ONBOARD:${employeeId}`;const[employee]=await db.select().from(hrEmployees).where(eq(hrEmployees.id,employeeId)).limit(1);if(!employee)return Response.json({error:"Сотрудник не найден"},{status:404});const assignment=resolveTaskAssignment(context,requestedAssignee,actor);if(!assignment.ok)return Response.json({error:assignment.error},{status:assignment.status});if(isTaskManager(context)&&assignment.assigneeEntityId&&!(await verifiedEntityId(assignment.assigneeEntityId)))return Response.json({error:"Ответственный не найден"},{status:400});const existing=await findScopedAutomationTask(db,context,key),existingResponse=scopedAutomationTaskResponse(existing);if(existingResponse)return existingResponse;const due=new Date();due.setUTCDate(due.getUTCDate()+21);const[task]=await db.insert(tasks).values({title:`Адаптация ${employeeId}`,owner:assignment.owner,dueDate:due.toISOString().slice(0,10),priority:"Высокий",status:"Входящие",sourceType:"Онбординг",sourceId:employeeId,description:"Оформление, доступы, наставник, обучение и контроль адаптации",assigneeEntityId:assignment.assigneeEntityId,kind:"HR-процесс",automationKey:key,requiresApproval:true,createdByUserId:context.appUserId,createdBy:actor}).returning();return Response.json({task},{status:201})}
async function personnelEvent(actor:string,body:Record<string,unknown>){const employeeId=clean(body.employeeId,80),eventType=clean(body.eventType,30),reason=clean(body.reason,400),amountMinor=Number(body.amountMinor??0);if(!["Премия","Депремирование","Нарушение"].includes(eventType)||reason.length<8||!Number.isInteger(amountMinor))return Response.json({error:"Укажите тип, сумму в копейках и проверяемое основание"},{status:400});const db=getDb(),[employee]=await db.select({id:hrEmployees.id}).from(hrEmployees).where(eq(hrEmployees.id,employeeId)).limit(1);if(!employee)return Response.json({error:"Сотрудник не найден"},{status:404});const id=`REW-${crypto.randomUUID().slice(0,8).toUpperCase()}`;const[row]=await db.insert(hrRewards).values({id,employeeId,eventType,amountMinor,reason,period:new Date().toISOString().slice(0,7),status:eventType==="Премия"?"На согласовании":"Зафиксировано"}).returning();await audit(actor,"hr.personnel_event_recorded","hr_reward",id,{employeeId,eventType,amountMinor});return Response.json({event:row},{status:201})}
async function terminate(actor:string,body:Record<string,unknown>){const employeeId=clean(body.employeeId,80),reason=clean(body.reason,400);if(reason.length<8)return Response.json({error:"Укажите документированную причину увольнения"},{status:400});const db=getDb();const[row]=await db.select().from(hrEmployees).where(eq(hrEmployees.id,employeeId)).limit(1);if(!row)return Response.json({error:"Сотрудник не найден"},{status:404});if(row.status==="Уволен")return Response.json({employee:row,reused:true});const now=new Date().toISOString();const[employee]=await db.update(hrEmployees).set({status:"Уволен",terminationDate:now.slice(0,10),terminationReason:reason,accessStatus:"Отозван",updatedAt:now}).where(eq(hrEmployees.id,employeeId)).returning();await db.update(hrAccesses).set({status:"Отозван",revokedAt:now,revocationReason:`Увольнение ${employeeId}: ${reason}`}).where(eq(hrAccesses.employeeId,employeeId));await db.update(entities).set({status:"Неактивна",updatedAt:now}).where(eq(entities.id,employeeId));await audit(actor,"hr.employee_terminated","hr_employee",employeeId,{reason,accesses:"revoked",history:"preserved"});return Response.json({employee,accessesRevoked:true,historyPreserved:true})}
async function audit(actor:string,action:string,entityType:string,entityId:string,payload:unknown){await getDb().insert(auditEvents).values({actor,action,entityType,entityId,payload:JSON.stringify(payload)})}
async function verifiedEntityId(candidate:string){if(!candidate)return "";const[entity]=await getDb().select({id:entities.id}).from(entities).where(eq(entities.id,candidate)).limit(1);return entity?.id??""}
function clean(value:unknown,max:number){return typeof value==="string"?value.trim().slice(0,max):""}
function employeeEntityStatus(status:string){return status==="Работает"?"Активна":status}
function employeeValues(body:Record<string,unknown>){
  const branchIds=stringArray(body.branchIds).map(value=>clean(value,80)).filter(Boolean).slice(0,20),branchNames=stringArray(body.branchNames).map(value=>clean(value,120)).filter(Boolean).slice(0,20);
  const displayName=clean(body.displayName,160),contact=clean(body.contact,160),unit=clean(body.unit,500)||branchNames.join(", "),positionId=clean(body.positionId,120),employmentType=clean(body.employmentType,80)||"Штат",contractId=clean(body.contractId,120),hireDate=clean(body.hireDate,20)||new Date().toISOString().slice(0,10),status=clean(body.status,40)||"Работает",note=clean(body.note,600);
  const rubles=Number(body.rateRubles??0),rateMinor=Math.round(rubles*100);
  if(displayName.length<3||unit.length<2||positionId.length<2)return {error:"Укажите ФИО, подразделение и должность"} as const;
  if(!Number.isFinite(rateMinor)||rateMinor<0)return {error:"Ставка должна быть положительным числом"} as const;
  if(!["Работает","На оформлении","Приостановлен"].includes(status))return {error:"Некорректный статус сотрудника"} as const;
  return {displayName,contact,unit,branchIds,branchNames,positionId,employmentType,contractId,hireDate,status,note,rateMinor};
}
function stringArray(value:unknown){return Array.isArray(value)?value.filter((item):item is string=>typeof item==="string"):[]}
