"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { createPortal } from "react-dom";
import { SoftSelect } from "./SoftSelect";
import "./FamilyWorkspace.css";
import "./DirectoryWorkspace.css";

type Family = { id:string;displayName:string;status:string;sourceSystem:string;sourceRecordId:string;dataQuality:string;scope:string;metadata:string };
type Member = Family & { entityType:string;profile:Record<string,unknown>;relation:string };
type Lead={id:string;firstClickAt:string;source:string;utmSource:string;utmMedium:string;utmCampaign:string;campaignId:string;managerEntityId:string;stage:string;status:string;childEntityId:string;contractId:string;serviceEntityId:string;dataQuality:string};
type FamilyRelationship={leads:Lead[];touchpoints:Array<{id:string;leadId:string;touchpointType:string;occurredAt:string;channel:string;outcome:string}>;stageEvents:Array<{id:number;leadId:string;fromStage:string;toStage:string;occurredAt:string}>;lifecycles:Array<{id:string;leadId:string;contractId:string;accrualId:string;paymentOperationId:string;serviceStartDate:string;monthlyValueMinor:number;ltvMinor:number;lifetimeMonths:number;status:string}>;accruals:Array<{id:string;contractId:string;amountMinor:number;dueDate:string;status:string;paymentOperationId:string}>;contracts:Array<{id:string;referenceDocumentId:string;number:string;signedStatus:string;status:string}>;contractDocuments:Array<{id:string;contractId:string;title:string;signedStatus:string;status:string}>;entityNames:Record<string,string>};
type FamilyDetail = { family:Family&{profile:Record<string,unknown>};hasDuplicate:boolean;members:Member[];operations:Array<{id:string;operationDate:string;amountMinor:number;direction:string;category:string;status:string;sourceSystem:string}>;students:Array<{id:string;childEntityId:string;groupId:string;cabinetStatus:string;status:string;group:{id:string;name:string}|null}>;relationship:FamilyRelationship };
const branches=["Атлас — садик","Атлас — школа","1–11","Небо","Лиственная"];

export function FamilyWorkspace({notify,onOpenIntegrations,onNavigate}:{notify:(message:string)=>void;onOpenIntegrations:()=>void;onNavigate:(module:"sales"|"legal"|"finance"|"education",focusId?:string)=>void}){
  const[families,setFamilies]=useState<Family[]>([]),[query,setQuery]=useState(""),[state,setState]=useState<"loading"|"ready"|"error">("loading"),[quality,setQuality]=useState("Все"),[editor,setEditor]=useState<"create"|FamilyDetail|null>(null),[network,setNetwork]=useState<FamilyDetail|null>(null),[networkLoadingId,setNetworkLoadingId]=useState(""),[busy,setBusy]=useState(false);
  const load=useCallback(async()=>{setState("loading");try{const params=new URLSearchParams({type:"Семья"});if(query.trim())params.set("q",query.trim());const response=await fetch(`/api/entities?${params}`,{cache:"no-store"}),payload=await response.json() as{entities?:Family[];error?:string};if(!response.ok)throw new Error(payload.error??"Не удалось загрузить семьи");setFamilies(payload.entities??[]);setState("ready")}catch{setState("error")}},[query]);
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),180);return()=>window.clearTimeout(timer)},[load]);
  const visible=families.filter(family=>quality==="Все"||(quality==="Готово"?!familyNeedsReview(family):familyNeedsReview(family)));
  async function openNetwork(familyId:string){setNetworkLoadingId(familyId);try{const response=await fetch(`/api/families?id=${encodeURIComponent(familyId)}`,{cache:"no-store"}),payload=await response.json() as FamilyDetail&{error?:string};if(!response.ok)throw new Error(payload.error??"Связи семьи недоступны");setNetwork(payload)}catch(error){notify(error instanceof Error?error.message:"Связи семьи недоступны")}finally{setNetworkLoadingId("")}}
  async function edit(familyId:string){setBusy(true);try{const response=await fetch(`/api/families?id=${encodeURIComponent(familyId)}`,{cache:"no-store"}),payload=await response.json() as FamilyDetail&{error?:string};if(!response.ok)throw new Error(payload.error??"Карточка недоступна");setEditor(payload)}catch(error){notify(error instanceof Error?error.message:"Карточка недоступна")}finally{setBusy(false)}}
  async function save(body:Record<string,unknown>){setBusy(true);try{const editing=editor&&editor!=="create"?editor:null,response=await fetch("/api/families",{method:editing?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(editing?{...body,familyId:editing.family.id,parentId:editing.members.find(member=>member.entityType==="Клиент")?.id,childId:editing.members.find(member=>member.entityType==="Ребёнок")?.id}:body)}),payload=await response.json() as{error?:string};if(!response.ok)throw new Error(payload.error??"Сохранение не выполнено");notify(editing?"Карточка семьи обновлена":"Семья добавлена. Доступ пока не выдан");setEditor(null);await load()}catch(error){notify(error instanceof Error?error.message:"Сохранение не выполнено")}finally{setBusy(false)}}
  return <section className="page family-workspace">
    <div className="page-heading family-page-heading"><div><p className="eyebrow">Клиент 360° · единый источник</p><h1>Клиенты и семьи</h1><p>Ручная карточка сохраняется сразу. Данные импорта и возможные дубли сверяются отдельно; доступ в личный кабинет выдаётся только явным действием.</p></div><div><button className="secondary-action" onClick={onOpenIntegrations}>Импорт из AlfaCRM</button><button className="primary-action" onClick={()=>setEditor("create")}>+ Семья вручную</button></div></div>
    <div className="client-data-rule"><strong>Карточка не равна доступу</strong><span>Ручной ввод подтверждён автором записи. Импорт и конфликты требуют сверки с источником. В обоих случаях приглашение родителю или ученику не отправляется автоматически.</span></div>
    <div className="family-toolbar"><label><span>⌕</span><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Найти семью по имени или ID"/></label><div className="family-quality-filter"><button className={quality==="Все"?"active":""} onClick={()=>setQuality("Все")}>Все {families.length}</button><button className={quality==="Нужна сверка"?"active":""} onClick={()=>setQuality("Нужна сверка")}>Нужна сверка {families.filter(familyNeedsReview).length}</button><button className={quality==="Готово"?"active":""} onClick={()=>setQuality("Готово")}>Готово {families.filter(family=>!familyNeedsReview(family)).length}</button></div></div>
    {state==="loading"?<div className="family-state"><strong>Загружаем семьи…</strong><span>Собираем единые карточки и связи.</span></div>:null}
    {state==="error"?<div className="family-state"><strong>Семьи временно недоступны</strong><button onClick={()=>void load()}>Повторить</button></div>:null}
    {state==="ready"&&!visible.length?<div className="family-state"><strong>Семей в этом списке пока нет</strong><span>Импортируйте данные из AlfaCRM или создайте семью вручную.</span><button onClick={()=>setEditor("create")}>+ Добавить семью</button></div>:null}
    {state==="ready"&&visible.length?<div className="family-grid">{visible.map(family=><article key={family.id}><button className="family-main" disabled={networkLoadingId===family.id} onClick={()=>void openNetwork(family.id)}><span>{family.id}</span><h2>{family.displayName}</h2><p>{family.scope}</p><small>{networkLoadingId===family.id?"Открываем карточку…":`${sourceLabel(family.sourceSystem)} · ${familyDataState(family)}`}</small></button><footer><span className={familyNeedsReview(family)?"review":"verified"}>{familyDataState(family)}</span><div><button disabled={busy} onClick={()=>void edit(family.id)}>Редактировать всё</button><button onClick={()=>onNavigate("legal",family.id)}>Договоры →</button></div></footer></article>)}</div>:null}
    {network?<FamilyDetailCard detail={network} close={()=>setNetwork(null)} edit={()=>{setNetwork(null);void edit(network.family.id)}} navigate={onNavigate}/>:null}
    {editor?<FamilyEditor detail={editor==="create"?null:editor} busy={busy} close={()=>setEditor(null)} submit={save}/>:null}
  </section>
}

function FamilyDetailCard({detail,close,edit,navigate}:{detail:FamilyDetail;close:()=>void;edit:()=>void;navigate:(module:"sales"|"legal"|"finance"|"education",focusId?:string)=>void}){
  const[view,setView]=useState<"Карточка"|"Связи">("Карточка"),profile=detail.family.profile,parent=detail.members.find(member=>member.entityType==="Клиент"),children=detail.members.filter(member=>member.entityType==="Ребёнок"),contract=detail.relationship.contracts[0],accrualTotal=detail.relationship.accruals.reduce((sum,row)=>sum+row.amountMinor,0);
  return createPortal(<div className="modal-layer family-network-layer"><button className="drawer-scrim" onClick={close} aria-label="Закрыть карточку семьи"/><section className="task-modal family-network family-detail-card" role="dialog" aria-modal="true" aria-labelledby="family-detail-title"><div className="drawer-head"><div><p>Клиенты · единая карточка</p><h2 id="family-detail-title">{detail.family.displayName}</h2><span>{detail.family.id} · {detail.family.scope} · {detail.family.status}</span></div><button onClick={close} aria-label="Закрыть">×</button></div>
    <nav className="family-detail-tabs"><button className={view==="Карточка"?"active":""} onClick={()=>setView("Карточка")}>Карточка семьи</button><button className={view==="Связи"?"active":""} onClick={()=>setView("Связи")}>Связи</button></nav>
    {view==="Карточка"?<div className="family-card-overview"><section><header><span>Семья</span><button onClick={edit}>Редактировать</button></header><dl><div><dt>Филиал</dt><dd>{str(profile.branch)||detail.family.scope}</dd></div><div><dt>Источник записи</dt><dd>{sourceLabel(detail.family.sourceSystem)}</dd></div><div><dt>Представитель</dt><dd>{parent?.displayName||"Не указан"}</dd></div><div><dt>Ответственный</dt><dd>{str(profile.familyManager)||"Не назначен"}</dd></div><div><dt>Адрес</dt><dd>{str(profile.address)||"Не указан"}</dd></div><div><dt>Состояние источника</dt><dd>{familyDataState(detail.family)}</dd></div><div><dt>Статус карточки</dt><dd>{detail.family.status}</dd></div><div><dt>Доступ</dt><dd>Выдаётся отдельно</dd></div></dl></section><section><header><span>Дети и обучение</span><b>{children.length}</b></header>{children.length?children.map(child=>{const student=detail.students.find(row=>row.childEntityId===child.id);return <button key={child.id} onClick={()=>navigate("education",student?.groupId||student?.id||child.id)}><strong>{child.displayName}</strong><small>{student?.group?.name||str(child.profile.groupName)||"Класс или группа не назначены"}</small><em>Открыть класс / группу →</em></button>}):<p>Дети пока не связаны с семьёй.</p>}</section><section><header><span>Договор и документы</span></header><button onClick={()=>navigate("legal",contract?.id||detail.family.id)}><strong>{contract?.number||str(profile.contractNumber)||"Договор не привязан"}</strong><small>{contract?`${contract.signedStatus} · ${detail.relationship.contractDocuments.length} документ(а)`:"Перейти в юридический реестр"}</small><em>Открыть документы →</em></button></section><section><header><span>Начисления и оплаты</span></header><button onClick={()=>navigate("finance",detail.family.id)}><strong>{rub(accrualTotal)}</strong><small>{detail.relationship.accruals.length} начислений · {detail.operations.length} операций</small><em>Открыть финансы семьи →</em></button></section></div>:<FamilyRelationshipGraph detail={detail} edit={edit} navigate={navigate}/>}
  </section></div>,document.body)
}

function FamilyRelationshipGraph({detail,edit,navigate}:{detail:FamilyDetail;edit:()=>void;navigate:(module:"sales"|"legal"|"finance"|"education",focusId?:string)=>void}){
  const lead=detail.relationship.leads[0],children=detail.members.filter(member=>member.entityType==="Ребёнок"),parent=detail.members.find(member=>member.entityType==="Клиент"),contract=detail.relationship.contracts[0],profile=detail.family.profile,touchpoints=lead?detail.relationship.touchpoints.filter(row=>row.leadId===lead.id):[],stageEvents=lead?detail.relationship.stageEvents.filter(row=>row.leadId===lead.id):[],funnelDuration=lead?daysBetween(lead.firstClickAt,stageEvents.at(-1)?.occurredAt||new Date().toISOString()):null,accrualTotal=detail.relationship.accruals.reduce((sum,row)=>sum+row.amountMinor,0),operationTotal=detail.operations.reduce((sum,row)=>sum+(row.direction==="Списание"?-row.amountMinor:row.amountMinor),0),contractNumber=contract?.number||str(profile.contractNumber)||lead?.contractId||"Договор не привязан",groupFocus=detail.students[0]?.groupId||detail.students[0]?.id||children[0]?.id;
  return <div className="family-graph-view"><div className="family-network-summary"><div><small>Источник</small><strong>{lead?.source||sourceLabel(detail.family.sourceSystem)}</strong></div><div><small>В воронке</small><strong>{funnelDuration===null?"Нет лида":`${funnelDuration} дн.`}</strong></div><div><small>Касаний</small><strong>{touchpoints.length}</strong></div><div><small>Дети</small><strong>{children.length}</strong></div><div><small>Начислено</small><strong>{rub(accrualTotal)}</strong></div></div><div className="family-network-canvas"><svg viewBox="0 0 1000 390" aria-hidden="true"><path d="M245 125 C340 125 350 195 430 195"/><path d="M570 195 C650 195 655 65 755 65"/><path d="M570 195 C650 195 655 195 755 195"/><path d="M570 195 C650 195 655 325 755 325"/></svg><button className="family-node source" disabled={!lead} onClick={()=>lead&&navigate("sales",lead.id)}><span>Продажи · источник</span><strong>{lead?.source||"Лид не связан"}</strong><small>{lead?`${lead.utmSource||"Без UTM"} / ${lead.utmMedium||"—"}`:"Добавьте связь с воронкой"}</small>{lead?<em>{lead.stage} · {funnelDuration} дн. · {touchpoints.length} касаний →</em>:null}</button><button className="family-node core" onClick={edit}><span>Единая карточка</span><strong>{detail.family.displayName}</strong><small>{parent?.displayName||"Представитель не указан"}</small><em>{detail.family.scope} · редактировать →</em></button><button className="family-node child" disabled={!children.length} onClick={()=>groupFocus&&navigate("education",groupFocus)}><span>Дети и обучение</span><strong>{children.map(child=>child.displayName).join(", ")||"Дети не связаны"}</strong><small>{detail.students.map(student=>student.group?.name).filter(Boolean).join(", ")||"Класс / группа не назначены"}</small>{children.length?<em>Открыть класс / группу →</em>:null}</button><button className="family-node contract" onClick={()=>navigate("legal",contract?.id||lead?.contractId||detail.family.id)}><span>Договор и документы</span><strong>{contractNumber}</strong><small>{contract?`${contract.signedStatus} · ${detail.relationship.contractDocuments.length} документ(а)`:"Перейти в юридический раздел"}</small><em>Открыть документы →</em></button><button className="family-node finance" onClick={()=>navigate("finance",detail.family.id)}><span>Начисления и оплаты</span><strong>{detail.relationship.accruals.length} начисл. · {detail.operations.length} операц.</strong><small>Начислено {rub(accrualTotal)} · сальдо {signedRub(operationTotal)}</small><em>Открыть финансы семьи →</em></button></div></div>
}

function FamilyEditor({detail,busy,close,submit}:{detail:FamilyDetail|null;busy:boolean;close:()=>void;submit:(body:Record<string,unknown>)=>Promise<void>}){
  const family=detail?.family,parent=detail?.members.find(member=>member.entityType==="Клиент"),child=detail?.members.find(member=>member.entityType==="Ребёнок"),familyProfile=family?.profile??{},parentProfile=parent?.profile??{},childProfile=child?.profile??{};
  function save(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget),body=Object.fromEntries(form.entries()) as Record<string,unknown>;body.sourceConfirmed=form.get("sourceConfirmed")==="on";void submit(body)}
  return createPortal(<div className="modal-layer family-editor-layer"><button className="drawer-scrim" onClick={close} aria-label="Закрыть"/><form className="task-modal family-editor" onSubmit={save}><div className="drawer-head"><div><p>Клиенты · полная карточка</p><h2>{detail?"Редактировать семью":"Добавить семью вручную"}</h2></div><button type="button" onClick={close}>×</button></div>
    <section><header><span>01</span><div><strong>Семья и филиал</strong><small>Основная карточка и область обслуживания</small></div></header><div className="family-editor-grid"><label><span>Название семьи</span><input name="familyName" required defaultValue={family?.displayName??""} placeholder="Семья Ивановых"/></label><label><span>Филиал</span><SoftSelect name="branch" ariaLabel="Филиал семьи" defaultValue={str(familyProfile.branch)||family?.scope||branches[0]} options={branches.map(value=>({value,label:value}))}/></label><label><span>Адрес</span><input name="address" defaultValue={str(familyProfile.address)} placeholder="Адрес проживания"/></label><label><span>Ответственный менеджер</span><input name="familyManager" defaultValue={str(familyProfile.familyManager)} placeholder="Сотрудник ArtHello"/></label><label><span>Теги</span><input name="tags" defaultValue={str(familyProfile.tags)} placeholder="Лояльный, льгота, несколько детей"/></label><label><span>Примечание</span><input name="note" defaultValue={str(familyProfile.note)} placeholder="Важная информация о семье"/></label><label className="wide"><span>Другие параметры семьи</span><textarea name="familyOther" defaultValue={extraLines(familyProfile,["branch","address","familyManager","contractNumber","billingPlan","financialNote","tags","note"])} placeholder={'Код скидки: FAMILY10\nИсточник обращения: рекомендация'}/></label></div></section>
    <section><header><span>02</span><div><strong>Родитель / представитель</strong><small>Контакт можно изменить до выдачи доступа</small></div></header><div className="family-editor-grid"><label><span>ФИО</span><input name="parentName" required defaultValue={parent?.displayName??""}/></label><label><span>Кем приходится</span><input name="parentRelation" defaultValue={str(parentProfile.relation)||"Родитель / представитель"}/></label><label><span>Телефон</span><input name="parentPhone" defaultValue={str(parentProfile.phone)} placeholder="+7…"/></label><label><span>Email</span><input name="parentEmail" type="email" defaultValue={str(parentProfile.email)} placeholder="name@example.ru"/></label><label className="wide"><span>Другие параметры представителя</span><textarea name="parentOther" defaultValue={extraLines(parentProfile,["phone","email","relation"])} placeholder="Параметр: значение"/></label></div></section>
    <section><header><span>03</span><div><strong>Ребёнок и обучение</strong><small>Класс, группа и занятия редактируются в этой карточке</small></div></header><div className="family-editor-grid"><label><span>ФИО ребёнка</span><input name="childName" required defaultValue={child?.displayName??""}/></label><label><span>Дата рождения</span><input name="birthDate" type="date" defaultValue={str(childProfile.birthDate)}/></label><label><span>Класс</span><input name="className" defaultValue={str(childProfile.className)} placeholder="3 класс"/></label><label><span>Группа</span><input name="groupName" defaultValue={str(childProfile.groupName)||detail?.students[0]?.group?.name||""} placeholder="3А / старшая группа"/></label><label><span>Основные занятия</span><textarea name="coreActivities" defaultValue={str(childProfile.coreActivities)} placeholder="Математика, русский язык…"/></label><label><span>Дополнительные занятия</span><textarea name="extraActivities" defaultValue={str(childProfile.extraActivities)} placeholder="Робототехника, футбол…"/></label><label className="wide"><span>Другие параметры ученика</span><textarea name="childOther" defaultValue={extraLines(childProfile,["birthDate","className","groupName","coreActivities","extraActivities"])} placeholder="Параметр: значение"/></label></div></section>
    <section><header><span>04</span><div><strong>Договор и финансы</strong><small>Привязки платежей редактируются; исходные сумма, дата и источник операции не переписываются</small></div></header><div className="family-editor-grid"><label><span>Номер договора</span><input name="contractNumber" defaultValue={str(familyProfile.contractNumber)}/></label><label><span>Тариф / схема начислений</span><input name="billingPlan" defaultValue={str(familyProfile.billingPlan)} placeholder="Основное обучение + доп. занятия"/></label><label className="wide"><span>ID финансовых операций</span><textarea name="operationIds" defaultValue={detail?.operations.map(operation=>operation.id).join("\n")??""} placeholder="По одному ID операции на строку"/><small>Можно добавить, удалить или перепривязать операцию. Каждое изменение фиксируется в аудите.</small></label><label className="wide"><span>Финансовое примечание</span><textarea name="financialNote" defaultValue={str(familyProfile.financialNote)} placeholder="Льгота, график оплаты, особенности начислений"/></label></div>{detail?.operations.length?<div className="linked-operations"><strong>Связанные операции: {detail.operations.length}</strong>{detail.operations.slice(0,4).map(operation=><span key={operation.id}>{operation.id} · {operation.operationDate} · {operation.category} · {rub(operation.amountMinor)} · {operation.status}</span>)}</div>:<div className="linked-operations empty"><strong>Финансовых операций пока нет</strong><span>Укажите ID после сверки платежа с этой семьёй.</span></div>}</section>
    {detail?.hasDuplicate?<div className="family-confirm"><span><strong>Найден возможный дубль</strong><small>Сначала объедините или разведите карточки в «Единых карточках». Самоподтверждение конфликт не снимает.</small></span></div>:detail&&family?.sourceSystem!=="MANUAL"&&family?.dataQuality!=="Проверено"?<label className="family-confirm"><input type="checkbox" name="sourceConfirmed"/><span><strong>Сверка внешнего источника завершена</strong><small>Отметьте только после сопоставления с AlfaCRM или импортным файлом. Доступ всё равно выдаётся отдельной кнопкой.</small></span></label>:<div className="family-confirm"><span><strong>Сохранение не выдаёт доступ</strong><small>{family?.sourceSystem==="MANUAL"||!detail?"Ручную карточку подтверждает автор при сохранении. Приглашение родителю или ученику выдаётся отдельно.":"Источник уже сверен. Изменение карточки не отправляет новое приглашение."}</small></span></div>}
    <div className="modal-actions"><button type="button" onClick={close}>Отмена</button><button disabled={busy}>{busy?"Сохраняем…":detail?"Сохранить изменения":"Создать семью"}</button></div>
  </form></div>,document.body)
}

function str(value:unknown){return typeof value==="string"?value:""}
function extraLines(profile:Record<string,unknown>,known:string[]){const knownSet=new Set(known);return Object.entries(profile).filter(([key])=>!knownSet.has(key)).map(([key,value])=>`${key}: ${typeof value==="string"?value:JSON.stringify(value)}`).join("\n")}
function sourceLabel(source:string){return source==="ALFACRM"?"AlfaCRM":source==="MANUAL"?"Ручной ввод":source.startsWith("SYNTHETIC")?"Тестовая карточка":source}
function familyDataState(family:Pick<Family,"sourceSystem"|"dataQuality">){return family.sourceSystem==="MANUAL"&&family.dataQuality!=="Требует сверки"?"Создано вручную":family.dataQuality}
function familyNeedsReview(family:Pick<Family,"sourceSystem"|"dataQuality">){return family.dataQuality==="Требует сверки"||family.dataQuality==="На проверке"||(family.sourceSystem!=="MANUAL"&&family.dataQuality!=="Проверено")}
function rub(minor:number){return new Intl.NumberFormat("ru-RU",{style:"currency",currency:"RUB",maximumFractionDigits:0}).format(minor/100)}
function signedRub(minor:number){return `${minor>0?"+":""}${rub(minor)}`}
function daysBetween(from:string,to:string){const start=Date.parse(from),end=Date.parse(to);return Number.isFinite(start)&&Number.isFinite(end)?Math.max(0,Math.ceil((end-start)/86400000)):0}
