CREATE TABLE IF NOT EXISTS "bank_alpha_reconciliation_runs" (
        "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
        "started_at" timestamp with time zone DEFAULT now(),
        "finished_at" timestamp with time zone,
        "status" text DEFAULT 'running',
        "bank_transactions_checked" integer DEFAULT 0,
        "crm_payments_checked" integer DEFAULT 0,
        "matched_count" integer DEFAULT 0,
        "partial_count" integer DEFAULT 0,
        "possible_count" integer DEFAULT 0,
        "unmatched_bank_count" integer DEFAULT 0,
        "unmatched_crm_count" integer DEFAULT 0,
        "excluded_internal_count" integer DEFAULT 0,
        "excluded_collection_count" integer DEFAULT 0,
        "excluded_bank_fee_count" integer DEFAULT 0,
        "needs_review_count" integer DEFAULT 0,
        "errors" jsonb DEFAULT '[]'::jsonb,
        "created_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "bank_alpha_reconciliation_matches" (
        "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
        "run_id" uuid,
        "bank_transaction_id" text,
        "crm_payment_id" uuid,
        "match_status" text,
        "match_confidence" text,
        "match_method" text,
        "amount_delta" numeric(15, 2),
        "date_delta_days" integer,
        "bank_amount" numeric(15, 2),
        "crm_amount" numeric(15, 2),
        "bank_date" date,
        "crm_date" date,
        "bank_counterparty_id" uuid,
        "bank_counterparty_name" text,
        "crm_customer_alpha_id" text,
        "student_id" uuid,
        "student_identity_id" uuid,
        "family_id" uuid,
        "reasons" jsonb DEFAULT '{}'::jsonb,
        "risk_flags" jsonb DEFAULT '{}'::jsonb,
        "created_at" timestamp with time zone DEFAULT now(),
        "updated_at" timestamp with time zone DEFAULT now()
);
