import { eq } from "drizzle-orm";
import { ensureCoreTables, getDb } from "../../../db";
import { auditEvents, entities, hrAccesses, hrCandidates, hrInterviews, hrRewards, hrEmployees, tasks } from "../../../db/schema";
import { nextCandidateStage } from "../../../lib/hr";
import { getRequestUser } from "../../../lib/request-user";

const editors=new Set(["OWNER","DIRECTOR","REPRESENTATIVE","HR"]);
export async function POST(request:Request){const actor=getRequestUser(request);if(!actor)return Response.json({error:"Требуется вход"},{status:401});const role=request.headers.get("x-arthello-role")??"";if(!editors.has(role))return Response.json({error:"Нет прав на HR-действие"},{status:403});try{await ensureCoreTables();const body=await request.json() as Record<string,unknown>,action=clean(body.action,50);if(action==="advanceCandidate")return advance(actor,body);if(action==="recordInterview")return interview(actor,body);if(action==="createOnboardingTask")return onboarding(actor,body);if(action==="recordPersonnelEvent")return personnelEvent(actor,body);if(action==="terminateEmployee")return terminate(actor,body);return Response.json({error:"Неизвестное действие"},{status:400})}catch(error){return Response.json({error:error instanceof Error?error.message:"Действие не выполнено"},{status:500})}}

async function advance(actor:string,body:Record<string,unknown>){const id=clean(body.candidateId,80),target=clean(body.targetStage,30),evidence=clean(body.evidence,500),db=getDb();const[row]=await db.select().from(hrCandidates).where(eq(hrCandidates.id,id)).limit(1);if(!row)return Response.json({error:"Кандидат не найден"},{status:404});if(!nextCandidateStage(row.stage,target)||evidence.length<8)return Response.json({error:"Допустим только следующий этап с доказательством"},{status:409});const[updated]=await db.update(hrCandidates).set({stage:target,evidence,updatedAt:new Date().toISOString()}).where(eq(hrCandidates.id,id)).returning();await audit(actor,"hr.candidate_advanced","hr_candidate",id,{from:row.stage,to:target,evidence});return Response.json({candidate:updated})}
async function interview(actor:string,body:Record<string,unknown>){const candidateId=clean(body.candidateId,80),summary=clean(body.summary,600),decision=clean(body.decision,100),score=Number(body.score);if(summary.length<10||!decision||!Number.isInteger(score)||score<0||score>100)return Response.json({error:"Нужны оценка 0–100, решение и итог интервью"},{status:400});const db=getDb();const[candidate]=await db.select().from(hrCandidates).where(eq(hrCandidates.id,candidateId)).limit(1);if(!candidate)return Response.json({error:"Кандидат не найден"},{status:404});const id=`INTV-${crypto.randomUUID().slice(0,8).toUpperCase()}`;const[row]=await db.insert(hrInterviews).values({id,candidateId,scheduledAt:new Date().toISOString(),interviewerEntityId:"EMP-T-HR-001",score,summary,decision}).returning();await audit(actor,"hr.interview_recorded","hr_interview",id,{candidateId,score,decision});return Response.json({interview:row},{status:201})}
async function onboarding(actor:string,body:Record<string,unknown>){const employeeId=clean(body.employeeId,80),db=getDb(),key=`HR_ONBOARD:${employeeId}`;const[employee]=await db.select().from(hrEmployees).where(eq(hrEmployees.id,employeeId)).limit(1);if(!employee)return Response.json({error:"Сотрудник не найден"},{status:404});const[existing]=await db.select().from(tasks).where(eq(tasks.automationKey,key)).limit(1);if(existing)return Response.json({task:existing,reused:true});const[task]=await db.insert(tasks).values({title:`Адаптация ${employeeId}`,owner:"HR T-H01",dueDate:"2026-09-15",priority:"Высокий",status:"Входящие",sourceType:"Онбординг",sourceId:employeeId,description:"Оформление, доступы, наставник, обучение и контроль адаптации",assigneeEntityId:"EMP-T-HR-001",kind:"HR-процесс",automationKey:key,requiresApproval:true,createdBy:actor}).returning();return Response.json({task},{status:201})}
async function personnelEvent(actor:string,body:Record<string,unknown>){const employeeId=clean(body.employeeId,80),eventType=clean(body.eventType,30),reason=clean(body.reason,400),amountMinor=Number(body.amountMinor??0);if(!["Премия","Депремирование","Нарушение"].includes(eventType)||reason.length<8||!Number.isInteger(amountMinor))return Response.json({error:"Укажите тип, сумму в копейках и проверяемое основание"},{status:400});const id=`REW-${crypto.randomUUID().slice(0,8).toUpperCase()}`;const[row]=await getDb().insert(hrRewards).values({id,employeeId,eventType,amountMinor,reason,period:"2026-08",status:eventType==="Премия"?"На согласовании":"Зафиксировано"}).returning();await audit(actor,"hr.personnel_event_recorded","hr_reward",id,{employeeId,eventType,amountMinor});return Response.json({event:row},{status:201})}
async function terminate(actor:string,body:Record<string,unknown>){const employeeId=clean(body.employeeId,80),reason=clean(body.reason,400);if(reason.length<8)return Response.json({error:"Укажите документированную причину увольнения"},{status:400});const db=getDb();const[row]=await db.select().from(hrEmployees).where(eq(hrEmployees.id,employeeId)).limit(1);if(!row)return Response.json({error:"Сотрудник не найден"},{status:404});if(row.status==="Уволен")return Response.json({employee:row,reused:true});const now=new Date().toISOString();const[employee]=await db.update(hrEmployees).set({status:"Уволен",terminationDate:now.slice(0,10),terminationReason:reason,accessStatus:"Отозван",updatedAt:now}).where(eq(hrEmployees.id,employeeId)).returning();await db.update(hrAccesses).set({status:"Отозван",revokedAt:now,revocationReason:`Увольнение ${employeeId}: ${reason}`}).where(eq(hrAccesses.employeeId,employeeId));await db.update(entities).set({status:"Неактивна",updatedAt:now}).where(eq(entities.id,employeeId));await audit(actor,"hr.employee_terminated","hr_employee",employeeId,{reason,accesses:"revoked",history:"preserved"});return Response.json({employee,accessesRevoked:true,historyPreserved:true})}
async function audit(actor:string,action:string,entityType:string,entityId:string,payload:unknown){await getDb().insert(auditEvents).values({actor,action,entityType,entityId,payload:JSON.stringify(payload)})}
function clean(value:unknown,max:number){return typeof value==="string"?value.trim().slice(0,max):""}
