import {desc,eq} from "drizzle-orm";
import {ensureCoreTables,getDb} from "../../../db";
import {auditEvents,legalChecks,legalContracts,legalDocumentItems,tasks} from "../../../db/schema";
import {nextLegalVersion} from "../../../lib/legal";
import {getRequestUser} from "../../../lib/request-user";
const editors=new Set(["OWNER","DIRECTOR","REPRESENTATIVE","LEGAL"]);
export async function POST(request:Request){const actor=getRequestUser(request);if(!actor)return Response.json({error:"Требуется вход"},{status:401});const role=request.headers.get("x-arthello-role")??"";if(!editors.has(role))return Response.json({error:"Нет прав на юридическое действие"},{status:403});try{await ensureCoreTables();const body=await request.json() as Record<string,unknown>,action=clean(body.action,50);if(action==="createDocumentVersion")return version(actor,body);if(action==="addDocument")return addDocument(actor,body);if(action==="createSignalTask")return signalTask(actor,body);if(action==="resolveSignal")return resolve(actor,body);return Response.json({error:"Неизвестное действие"},{status:400})}catch(error){return Response.json({error:error instanceof Error?error.message:"Действие не выполнено"},{status:500})}}
async function version(actor:string,body:Record<string,unknown>){const stableId=clean(body.stableId,80),reference=clean(body.reference,300),db=getDb();if(reference.length<5)return Response.json({error:"Укажите основание или ссылку новой версии"},{status:400});const[latest]=await db.select().from(legalDocumentItems).where(eq(legalDocumentItems.stableId,stableId)).orderBy(desc(legalDocumentItems.version)).limit(1);if(!latest)return Response.json({error:"Документ не найден"},{status:404});const v=nextLegalVersion(latest.version),id=`${stableId}-V${v}`;const[row]=await db.insert(legalDocumentItems).values({...latest,id,version:v,reference,status:"На проверке",createdAt:new Date().toISOString()}).returning();await audit(actor,"legal.document_version_added","legal_document",stableId,{from:latest.version,to:v,reference});return Response.json({document:row},{status:201})}
async function addDocument(actor:string,body:Record<string,unknown>){const contractId=clean(body.contractId,80),itemType=clean(body.itemType,40),title=clean(body.title,200),reference=clean(body.reference,300),db=getDb();if(!contractId||!itemType||title.length<4)return Response.json({error:"Укажите договор, тип и название"},{status:400});const[contract]=await db.select().from(legalContracts).where(eq(legalContracts.id,contractId)).limit(1);if(!contract)return Response.json({error:"Договор не найден"},{status:404});const stableId=`LGLDOC-${crypto.randomUUID().slice(0,8).toUpperCase()}`,id=`${stableId}-V1`;const[row]=await db.insert(legalDocumentItems).values({id,stableId,contractId,itemType,title,version:1,required:false,signedStatus:"Не подписано",status:reference?"На проверке":"Метаданные",reference}).returning();await audit(actor,"legal.document_added","legal_document",stableId,{contractId,itemType});return Response.json({document:row},{status:201})}
async function signalTask(actor:string,body:Record<string,unknown>){const id=clean(body.signalId,80),db=getDb(),key=`LEGAL_SIGNAL:${id}`;const[signal]=await db.select().from(legalChecks).where(eq(legalChecks.id,id)).limit(1);if(!signal)return Response.json({error:"Сигнал не найден"},{status:404});const[existing]=await db.select().from(tasks).where(eq(tasks.automationKey,key)).limit(1);if(existing)return Response.json({task:existing,reused:true});const[task]=await db.insert(tasks).values({title:signal.recommendation,owner:"Юрист T-L01",dueDate:"2026-08-28",priority:signal.severity==="Критичный"?"Критичный":"Высокий",status:"Входящие",sourceType:"Юридический сигнал",sourceId:id,description:`${signal.evidence}. Проверить документы и зафиксировать решение без обвинений.`,assigneeEntityId:"EMP-T-LEGAL-001",kind:"Автозадача",automationKey:key,requiresApproval:true,createdBy:actor}).returning();await db.update(legalChecks).set({relatedTaskId:task.id,status:"В работе"}).where(eq(legalChecks.id,id));return Response.json({task},{status:201})}
async function resolve(actor:string,body:Record<string,unknown>){const id=clean(body.signalId,80),resolution=clean(body.resolution,600);if(resolution.length<12)return Response.json({error:"Нужно проверяемое основание закрытия"},{status:400});const db=getDb();const[signal]=await db.select().from(legalChecks).where(eq(legalChecks.id,id)).limit(1);if(!signal)return Response.json({error:"Сигнал не найден"},{status:404});if(signal.status==="Закрыт")return Response.json({signal,reused:true});const[row]=await db.update(legalChecks).set({status:"Закрыт",resolution,resolvedAt:new Date().toISOString()}).where(eq(legalChecks.id,id)).returning();await audit(actor,"legal.signal_resolved","legal_check",id,{resolution});return Response.json({signal:row})}
async function audit(actor:string,action:string,entityType:string,entityId:string,payload:unknown){await getDb().insert(auditEvents).values({actor,action,entityType,entityId,payload:JSON.stringify(payload)})}
function clean(value:unknown,max:number){return typeof value==="string"?value.trim().slice(0,max):""}
