services:
  school:
    build:
      context: ..
      dockerfile: deploy/Dockerfile.offline
    networks:
      - arthello_public

networks:
  arthello_public:
    external: true
    name: arthello-os_public
