import { Router, type IRouter } from "express";
import { healthRouter } from "./health.js";
import { branchesRouter } from "./branches.js";
import { marketingRouter } from "./marketing.js";
import { financeRouter } from "./finance.js";
import { integrationsRouter } from "./integrations.js";
import { webhooksRouter } from "./webhooks.js";
import { identityRouter } from "./identity.js";
import { timelineRouter } from "./timeline.js";
import { bankingRouter } from "./banking.js";
import { ledgerRouter } from "./ledger.js";
import { reconciliationRouter } from "./reconciliation.js";
import { staffRouter } from "./staff.js";
import { pnlRouter } from "./pnl.js";
import { contractorsModuleRouter } from "./contractors-module.js";
import { taxesModuleRouter } from "./taxes-module.js";
import { testDataRouter } from "./test-data.js";
import { staffCompleteRouter } from "./staff-complete.js";
import { trustScoreRouter } from "./trust-score.js";
import { monthClosingRouter } from "./month-closing.js";
import { cfoRouter } from "./cfo.js";
import { bankingAnalyticsRouter } from "./banking-analytics.js";
import { financeQaRouter } from "./finance-qa.js";
import { articlesModuleRouter } from "./articles-module.js";
import { documentsModuleRouter } from "./documents-module.js";
import { staffHrRouter } from "./staff-hr.js";
import { authRouter } from "./auth.js";
import { peopleAccessRouter } from "./people-access.js";
import { contractsModuleRouter } from "./contracts-module.js";
import { educationalModuleRouter } from "./educational-module.js";
import { scheduleModuleRouter } from "./schedule-module.js";
import { bankingMatchRouter } from "./banking-match.js";
import { financialCoreRouter } from "./financial-core.js";
import { systemAuditRouter } from "./system-audit.js";
import { categorizationRouter } from "./categorization.js";
import { recurringRouter } from "./recurring.js";
import { payablesRouter } from "./payables.js";
import { coverageRouter } from "./coverage.js";
import { coverageAuditRouter } from "./coverage/index.js";
import { evotorRouter } from "./evotor.js";
import { employeesModuleRouter } from "./employees-module.js";
import { frontOfficeRouter } from "./front-office.js";
import { smsVizitkaShadowRouter } from "./front-office-smsvizitka.js";
import { paymentsRouter } from "./payments.js";

export const apiRouter: IRouter = Router();

apiRouter.use(healthRouter);
apiRouter.use(branchesRouter);
apiRouter.use(marketingRouter);
apiRouter.use(financeRouter);
apiRouter.use(integrationsRouter);
apiRouter.use(webhooksRouter);
apiRouter.use(identityRouter);
apiRouter.use(timelineRouter);
apiRouter.use(bankingRouter);
apiRouter.use(bankingMatchRouter);
apiRouter.use(financialCoreRouter);
apiRouter.use(ledgerRouter);
apiRouter.use(reconciliationRouter);
apiRouter.use(staffRouter);
apiRouter.use(pnlRouter);
apiRouter.use(contractorsModuleRouter);
apiRouter.use(taxesModuleRouter);
apiRouter.use(testDataRouter);
apiRouter.use(staffCompleteRouter);
apiRouter.use(trustScoreRouter);
apiRouter.use(monthClosingRouter);
apiRouter.use(cfoRouter);
apiRouter.use(bankingAnalyticsRouter);
apiRouter.use(financeQaRouter);
apiRouter.use(articlesModuleRouter);
apiRouter.use(documentsModuleRouter);
apiRouter.use(staffHrRouter);
apiRouter.use(authRouter);
apiRouter.use(peopleAccessRouter);
apiRouter.use(contractsModuleRouter);
apiRouter.use(educationalModuleRouter);
apiRouter.use(scheduleModuleRouter);
apiRouter.use(systemAuditRouter);
apiRouter.use(categorizationRouter);
apiRouter.use(recurringRouter);
apiRouter.use(payablesRouter);
apiRouter.use(coverageRouter);
apiRouter.use(coverageAuditRouter);
apiRouter.use(evotorRouter);
apiRouter.use(employeesModuleRouter);
apiRouter.use(frontOfficeRouter);
apiRouter.use(smsVizitkaShadowRouter);
apiRouter.use(paymentsRouter);
