import { Router, type IRouter } from "express";
import healthRouter from "./health";
import syncRouter from "./sync";
import branchesRouter from "./branches";
import marketingRouter from "./marketing";
import { financeRouter } from "./finance";
import { integrationsRouter } from "./integrations";
import { webhooksRouter } from "./webhooks";
import { identityRouter } from "./identity";
import { timelineRouter } from "./timeline";
import { bankingRouter } from "./banking";
import { ledgerRouter } from "./ledger";
import { reconciliationRouter } from "./reconciliation";
import { staffRouter } from "./staff";
import { pnlRouter } from "./pnl";
import { contractorsModuleRouter } from "./contractors-module";
import { taxesModuleRouter } from "./taxes-module";
import { testDataRouter } from "./test-data";
import { staffCompleteRouter } from "./staff-complete";
import { trustScoreRouter } from "./trust-score";
import { monthClosingRouter } from "./month-closing";
import { cfoRouter } from "./cfo";
import { bankingAnalyticsRouter } from "./banking-analytics";
import { financeQaRouter } from "./finance-qa";
import { articlesModuleRouter } from "./articles-module";
import { documentsModuleRouter } from "./documents-module";
import { staffHrRouter } from "./staff-hr";
import { authRouter } from "./auth";
import { contractsModuleRouter } from "./contracts-module";
import { educationalModuleRouter } from "./educational-module";
import { scheduleModuleRouter } from "./schedule-module";
import { bankingMatchRouter } from "./banking-match";
import { financialCoreRouter } from "./financial-core";
import { systemAuditRouter } from "./system-audit";
import { categorizationRouter } from "./categorization";
import { recurringRouter } from "./recurring";
import { payablesRouter } from "./payables";
import { coverageRouter } from "./coverage";
import { auditRouter } from "./audit";
import { evotorRouter } from "./evotor";
import { employeesModuleRouter } from "./employees-module";
import { frontOfficeRouter } from "./front-office";
import { smsVizitkaShadowRouter } from "./front-office-smsvizitka";

const router: IRouter = Router();

router.use(healthRouter);
router.use(syncRouter);
router.use(branchesRouter);
router.use(marketingRouter);
router.use(financeRouter);
router.use(integrationsRouter);
router.use(webhooksRouter);
router.use(identityRouter);
router.use(timelineRouter);
router.use(bankingRouter);
router.use(bankingMatchRouter);
router.use(financialCoreRouter);
router.use(ledgerRouter);
router.use(reconciliationRouter);
router.use(staffRouter);
router.use(pnlRouter);
router.use(contractorsModuleRouter);
router.use(taxesModuleRouter);
router.use(testDataRouter);
router.use(staffCompleteRouter);
router.use(trustScoreRouter);
router.use(monthClosingRouter);
router.use(cfoRouter);
router.use(bankingAnalyticsRouter);
router.use(financeQaRouter);
router.use(articlesModuleRouter);
router.use(documentsModuleRouter);
router.use(staffHrRouter);
router.use(authRouter);
router.use(contractsModuleRouter);
router.use(educationalModuleRouter);
router.use(scheduleModuleRouter);
router.use(systemAuditRouter);
router.use(categorizationRouter);
router.use(recurringRouter);
router.use(payablesRouter);
router.use(coverageRouter);
router.use(auditRouter);
router.use(evotorRouter);
router.use(employeesModuleRouter);
router.use(frontOfficeRouter);
router.use(smsVizitkaShadowRouter);

export default router;
