import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import branchesRouter from "./branches.js";
import marketingRouter from "./marketing.js";
import { financeRouter } from "./finance.js";
import { integrationsRouter } from "./integrations.js";
import { webhooksRouter } from "./webhooks.js";
import { identityRouter } from "./identity.js";
import { timelineRouter } from "./timeline.js";
import { bankingRouter } from "./banking.js";
import { ledgerRouter } from "./ledger.js";
import { reconciliationRouter } from "./reconciliation.js";
import { staffRouter } from "./staff.js";
import { pnlRouter } from "./pnl.js";
import { contractorsModuleRouter } from "./contractors-module.js";
import { taxesModuleRouter } from "./taxes-module.js";
import { testDataRouter } from "./test-data.js";
import { staffCompleteRouter } from "./staff-complete.js";
import { trustScoreRouter } from "./trust-score.js";
import { monthClosingRouter } from "./month-closing.js";
import { cfoRouter } from "./cfo.js";
import { bankingAnalyticsRouter } from "./banking-analytics.js";
import { financeQaRouter } from "./finance-qa.js";
import { articlesModuleRouter } from "./articles-module.js";
import { documentsModuleRouter } from "./documents-module.js";
import { staffHrRouter } from "./staff-hr.js";
import { authRouter } from "./auth.js";
import { peopleAccessRouter } from "./people-access.js";
import { contractsModuleRouter } from "./contracts-module.js";
import { educationalModuleRouter } from "./educational-module.js";
import { scheduleModuleRouter } from "./schedule-module.js";
import { bankingMatchRouter } from "./banking-match.js";
import { financialCoreRouter } from "./financial-core.js";
import { systemAuditRouter } from "./system-audit.js";
import { categorizationRouter } from "./categorization.js";
import { recurringRouter } from "./recurring.js";
import { payablesRouter } from "./payables.js";
import { coverageRouter } from "./coverage.js";
import { auditRouter } from "./audit.js";
import { evotorRouter } from "./evotor.js";
import { employeesModuleRouter } from "./employees-module.js";
import { frontOfficeRouter } from "./front-office.js";
import { smsVizitkaShadowRouter } from "./front-office-smsvizitka.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use(branchesRouter);
router.use(marketingRouter);
router.use(financeRouter);
router.use(integrationsRouter);
router.use(webhooksRouter);
router.use(identityRouter);
router.use(timelineRouter);
router.use(bankingRouter);
router.use(bankingMatchRouter);
router.use(financialCoreRouter);
router.use(ledgerRouter);
router.use(reconciliationRouter);
router.use(staffRouter);
router.use(pnlRouter);
router.use(contractorsModuleRouter);
router.use(taxesModuleRouter);
router.use(testDataRouter);
router.use(staffCompleteRouter);
router.use(trustScoreRouter);
router.use(monthClosingRouter);
router.use(cfoRouter);
router.use(bankingAnalyticsRouter);
router.use(financeQaRouter);
router.use(articlesModuleRouter);
router.use(documentsModuleRouter);
router.use(staffHrRouter);
router.use(authRouter);
router.use(peopleAccessRouter);
router.use(contractsModuleRouter);
router.use(educationalModuleRouter);
router.use(scheduleModuleRouter);
router.use(systemAuditRouter);
router.use(categorizationRouter);
router.use(recurringRouter);
router.use(payablesRouter);
router.use(coverageRouter);
router.use(auditRouter);
router.use(evotorRouter);
router.use(employeesModuleRouter);
router.use(frontOfficeRouter);
router.use(smsVizitkaShadowRouter);

export default router;
