import { asc } from "drizzle-orm";
import { ensureCoreTables, getDb } from "../../../db";
import { educationAttendance, educationCommunications, educationFeedback, educationGroups, educationLessons, educationPrograms, educationProgress, educationStudents, entities } from "../../../db/schema";
import { attendanceSummary, educationScope, progressBand } from "../../../lib/education";
import { getRequestUser } from "../../../lib/request-user";

const roleEntity:Record<string,string>={TEACHER:"EMP-T-032",PARENT:"FAM-T-014"};
export async function GET(request:Request){const actor=getRequestUser(request);if(!actor)return Response.json({error:"Требуется вход"},{status:401});const role=request.headers.get("x-arthello-role")??"";const scope=educationScope(role,roleEntity[role]??"");if(scope.kind==="none")return Response.json({error:"Нет доступа к образовательному контуру"},{status:403});try{await ensureCoreTables();const db=getDb();const [programs,allGroups,allStudents,allLessons,allAttendance,allProgress,allFeedback,allCommunications,entityRows]=await Promise.all([db.select().from(educationPrograms).orderBy(asc(educationPrograms.title)),db.select().from(educationGroups),db.select().from(educationStudents),db.select().from(educationLessons).orderBy(asc(educationLessons.scheduledAt)),db.select().from(educationAttendance),db.select().from(educationProgress),db.select().from(educationFeedback),db.select().from(educationCommunications).orderBy(asc(educationCommunications.createdAt)),db.select({id:entities.id,displayName:entities.displayName}).from(entities)]);
let groups=allGroups,students=allStudents;if(scope.kind==="teacher")groups=allGroups.filter(row=>row.teacherEntityId===scope.id);if(scope.kind==="family")students=allStudents.filter(row=>row.familyEntityId===scope.id);if(scope.kind!=="all"){const groupIds=new Set(scope.kind==="teacher"?groups.map(row=>row.id):students.map(row=>row.groupId));groups=allGroups.filter(row=>groupIds.has(row.id));students=allStudents.filter(row=>groupIds.has(row.groupId)&&(scope.kind!=="family"||row.familyEntityId===scope.id));}
const groupIds=new Set(groups.map(row=>row.id)),studentIds=new Set(students.map(row=>row.id));const lessons=allLessons.filter(row=>groupIds.has(row.groupId));const lessonIds=new Set(lessons.map(row=>row.id));const attendance=allAttendance.filter(row=>lessonIds.has(row.lessonId)&&studentIds.has(row.studentId));const progress=allProgress.filter(row=>studentIds.has(row.studentId)).map(row=>({...row,band:progressBand(row.score)}));const feedback=allFeedback.filter(row=>studentIds.has(row.studentId));const communications=allCommunications.filter(row=>row.audienceType==="Группа"?groupIds.has(row.audienceId):scope.kind==="all"||row.audienceId===scope.id);const entityNames=Object.fromEntries(entityRows.map(row=>[row.id,row.displayName]));return Response.json({scope,programs:programs.filter(row=>groups.some(group=>group.programId===row.id)),groups,students,lessons,attendance,progress,feedback,communications,entityNames,summary:{groups:groups.length,students:students.length,lessonsToday:lessons.filter(row=>row.scheduledAt.startsWith("2026-08-21")).length,attendance:attendanceSummary(attendance),openFeedback:feedback.filter(row=>row.status!=="Закрыто").length},chain:{programId:"PRG-T-012",teacherId:"EMP-T-032",groupId:"GRP-T-3A",lessonId:"LES-T-3A-0821",attendanceId:"ATT-T-014",progressId:"PROG-T-014",feedbackId:"FDB-T-014"},privacy:"Медицинские сведения отсутствуют в ответе. Родительский тестовый режим ограничен FAM-T-014; педагогический — назначенными группами EMP-T-032."});}catch(error){return Response.json({error:error instanceof Error&&error.message.includes("D1 binding")?"База обучения ещё не подключена":"Не удалось загрузить обучение"},{status:503})}}
