"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import Image from "next/image";

type PlanItem = { id: string; scheduledAt: string; accountId: string; authorEntityId: string; format: string; topic: string; offerId: string; campaignId: string; status: string; brief: string };
type Publication = { id: string; planItemId: string; publishedAt: string; publicationRef: string; reach: number; views: number; reactions: number; clicks: number; leads: number; contracts: number; revenueMinor: number; dataQuality: string; rates: { engagementPercent: number; clickPercent: number; leadPercent: number; contractPercent: number }; planItem?: PlanItem; account?: { id: string; platform: string; displayName: string } };
type ContentData = {
  accounts: Array<{ id: string; platform: string; displayName: string; status: string; audienceCount: number; sourceType: string }>;
  plan: PlanItem[]; publications: Publication[];
  recommendations: Array<{ id: string; publicationId: string; signalType: string; evidence: string; recommendation: string; status: string; relatedTaskId: number | null }>;
  entityNames: Record<string, string>;
  summary: { reach: number; views: number; reactions: number; clicks: number; leads: number; contracts: number; revenueMinor: number };
  chain: Array<{ id: string; publicationId: string; clickId: string; leadId: string; contractId: string; paymentOperationId: string; revenueMinor: number; attributionModel: string; publication?: Publication; planItem?: PlanItem; lead?: { id: string; source: string; campaignId: string; offerId: string }; payment?: { id: string; amountMinor: number; operationDate: string; dataQuality: string } }>;
  sourcePolicy: { status: string; note: string; ranking: string };
};

type Tab = "overview" | "studio" | "plan" | "publications" | "chain" | "recommendations";
const tabs: Array<{ id: Tab; label: string }> = [{ id: "overview", label: "Обзор" }, { id: "studio", label: "Студия" }, { id: "plan", label: "Контент-план" }, { id: "publications", label: "Публикации" }, { id: "chain", label: "До выручки" }, { id: "recommendations", label: "Рекомендации" }];
const roleCodes: Record<string, string> = { "Собственник": "OWNER", "Директор": "DIRECTOR", "Маркетинг": "MARKETING", "Представитель Виталия": "REPRESENTATIVE", "Продажи": "SALES", "Финансы": "FINANCE", "Педагог": "TEACHER" };
const rub = new Intl.NumberFormat("ru-RU", { style: "currency", currency: "RUB", maximumFractionDigits: 0 });
const number = new Intl.NumberFormat("ru-RU");
const rubles = (minor: number) => rub.format(minor / 100);
const date = (value: string) => new Date(value).toLocaleDateString("ru-RU", { day: "2-digit", month: "short" });

export function ContentWorkspace({ role, notify, onTasksChanged, onOpenSales, onOpenFinance, sourceOnly = false }: { role: string; notify: (value: string) => void; onTasksChanged: () => void; onOpenSales: () => void; onOpenFinance: () => void; sourceOnly?: boolean }) {
  const [data, setData] = useState<ContentData | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [tab, setTab] = useState<Tab>("overview"); const [busy, setBusy] = useState(""); const [createOpen, setCreateOpen] = useState(false); const [publishId, setPublishId] = useState(""); const [publicationRef, setPublicationRef] = useState(""); const [prompt, setPrompt] = useState(""); const [reference, setReference] = useState<File | null>(null); const [generated, setGenerated] = useState(""); const [generationError, setGenerationError] = useState("");
  const load = useCallback(async () => { try { const response = await fetch("/api/content", { cache: "no-store" }); const payload = await response.json() as ContentData & { error?: string }; if (!response.ok) throw new Error(payload.error ?? "Не удалось загрузить контент"); setData(payload); setError(""); } catch (loadError) { setError(loadError instanceof Error ? loadError.message : "Не удалось загрузить контент"); } finally { setLoading(false); } }, []);
  useEffect(() => { const handle = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(handle); }, [load]);
  async function action(body: Record<string, unknown>, key: string) { setBusy(key); try { const response = await fetch("/api/content-actions", { method: "POST", headers: { "content-type": "application/json", "x-arthello-role": roleCodes[role] ?? "" }, body: JSON.stringify(body) }); const payload = await response.json() as { error?: string; reused?: boolean }; if (!response.ok) throw new Error(payload.error ?? "Действие не выполнено"); notify(payload.reused ? "Связанная запись уже существует" : "Действие контента сохранено"); await load(); onTasksChanged(); return true; } catch (actionError) { notify(actionError instanceof Error ? actionError.message : "Действие не выполнено"); return false; } finally { setBusy(""); } }
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); if (await action({ action: "createPlanItem", ...Object.fromEntries(form.entries()) }, "create")) setCreateOpen(false); }
  async function generate(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy("generate"); setGenerationError(""); try { const form = new FormData(event.currentTarget); if (reference) form.set("reference", reference); const response = await fetch("/api/content-generate", { method: "POST", headers: { "x-arthello-role": roleCodes[role] ?? "" }, body: form }); const payload = await response.json() as { imageDataUrl?: string; error?: string; needsCredential?: boolean }; if (!response.ok || !payload.imageDataUrl) throw new Error(payload.error ?? "Изображение не создано"); setGenerated(payload.imageDataUrl); notify("Изображение создано. Оно не сохранено в базе — скачайте или добавьте в контент-план."); } catch (cause) { const message = cause instanceof Error ? cause.message : "Изображение не создано"; setGenerationError(message); notify(message); } finally { setBusy(""); } }
  const maxViews = useMemo(() => Math.max(...(data?.publications.map((row) => row.views) ?? [1])), [data]);
  const activeTab = sourceOnly ? "studio" : tab;
  if (loading) return <section className="content-loading">Собираем контент до выручки…</section>;
  if (error || !data) return <section className="content-loading"><strong>{error || "Нет данных"}</strong></section>;
  return <section className="page content-workspace">
    <div className="content-heading"><div><p className="eyebrow">Контент-студия ArtHello</p><h1>Контент и маркетинг</h1><p>{sourceOnly ? "Создавайте визуалы на основе описания и референсов. План и аналитика появятся после подключения выбранных каналов." : "План, публикации и метрики объединены с переходами, заявками, договорами и выручкой."}</p></div>{!sourceOnly ? <button onClick={() => setCreateOpen(true)}>+ Материал в план</button> : null}</div>
    {sourceOnly ? <div className="content-boundary"><strong>Студия готова</strong><span>Для генерации подключите OpenAI Images. Результат появится только после реального ответа сервиса.</span><em>данные не сохраняются автоматически</em></div> : <><div className="content-boundary"><strong>Тестовые данные</strong><span>{data.sourcePolicy.note}</span><em>{data.sourcePolicy.ranking}</em></div>
    <div className="content-kpis"><button onClick={() => setTab("publications")}><span>Охват</span><strong>{number.format(data.summary.reach)}</strong><small>{number.format(data.summary.views)} просмотров</small></button><button onClick={() => setTab("publications")}><span>Переходы</span><strong>{number.format(data.summary.clicks)}</strong><small>{data.summary.views ? (data.summary.clicks / data.summary.views * 100).toFixed(1) : 0}% от просмотров</small></button><button onClick={() => setTab("chain")}><span>Заявки → договоры</span><strong>{data.summary.leads} → {data.summary.contracts}</strong><small>по сохранённой атрибуции</small></button><button className="positive" onClick={() => setTab("chain")}><span>Выручка</span><strong>{rubles(data.summary.revenueMinor)}</strong><small>синтетический финансовый след</small></button></div>
    <div className="content-tabs">{tabs.map((item) => <button key={item.id} className={activeTab === item.id ? "active" : ""} onClick={() => setTab(item.id)}>{item.label}{item.id === "recommendations" ? <b>{data.recommendations.filter((row) => row.status !== "Закрыта").length}</b> : null}</button>)}</div></>}

    {activeTab === "overview" ? <div className="content-overview"><article className="content-panel"><Head eyebrow="Бизнес-результат" title="Публикации по доказанному эффекту" aside="выручка → договор → лид" /><div className="content-ranking">{data.publications.map((row, index) => <button key={row.id} onClick={() => setTab("publications")}><span>{String(index + 1).padStart(2, "0")}</span><div><strong>{row.planItem?.topic}</strong><small>{row.account?.platform} · {row.planItem?.format}</small><i><b style={{ width: `${Math.max(5, row.views / maxViews * 100)}%` }} /></i></div><em>{row.contracts ? `${row.contracts} договор` : `${row.leads} заявок`}</em><strong>{row.revenueMinor ? rubles(row.revenueMinor) : "—"}</strong></button>)}</div></article><article className="content-panel"><Head eyebrow="Каналы" title="Аккаунты" aside={`${data.accounts.length} контура`} /><div className="account-list">{data.accounts.map((account) => <article key={account.id}><span>{account.platform.slice(0,2).toUpperCase()}</span><div><strong>{account.displayName}</strong><small>{number.format(account.audienceCount)} аудитория</small></div><em>{account.status}</em></article>)}</div></article><article className="content-panel content-calendar"><Head eyebrow="Ближайшие материалы" title="Операционный план" aside="авторы назначены" /><div>{data.plan.slice(-3).map((item) => <article key={item.id}><time>{date(item.scheduledAt)}</time><span><strong>{item.topic}</strong><small>{data.accounts.find((row) => row.id === item.accountId)?.platform} · {item.format} · {data.entityNames[item.authorEntityId]}</small></span><em>{item.status}</em></article>)}</div></article></div> : null}

    {activeTab === "studio" ? <div className="content-studio">
      <form className="content-panel studio-form" onSubmit={generate}>
        <Head eyebrow="OpenAI Images" title="Создать изображение" aside="описание + ваш референс" />
        <label><span>Что нужно создать</span><textarea name="prompt" value={prompt} onChange={(event) => setPrompt(event.target.value)} minLength={12} required placeholder="Например: спокойная предметная фотография учебной мастерской ArtHello, белый фон, чёрные детали, один красный акцент…" /></label>
        <div><label><span>Формат</span><select name="size" defaultValue="1024x1024"><option value="1024x1024">Квадрат 1:1</option><option value="1536x1024">Горизонтальный 3:2</option><option value="1024x1536">Вертикальный 2:3</option></select></label><label><span>Качество</span><select name="quality" defaultValue="medium"><option value="low">Черновик</option><option value="medium">Стандарт</option><option value="high">Высокое</option></select></label></div>
        <label className="reference-upload"><span>Референс ArtHello — необязательно</span><input type="file" accept="image/png,image/jpeg,image/webp" onChange={(event) => setReference(event.target.files?.[0] ?? null)} /><small>{reference ? `${reference.name} · ${(reference.size / 1024 / 1024).toFixed(1)} МБ` : "PNG, JPEG или WebP до 8 МБ"}</small></label>
        <div className="studio-privacy"><strong>Контроль данных</strong><span>Картинка отправляется в OpenAI только после нажатия. ArtHello OS не хранит референс и результат в текущей версии.</span></div>
        {generationError ? <div className="studio-error"><strong>Генерация пока недоступна</strong><span>{generationError}</span><small>Настройте OpenAI Images в Центре интеграций и добавьте ключ в защищённые переменные staging.</small></div> : null}
        <button disabled={busy === "generate"}>{busy === "generate" ? "Создаём изображение…" : "Создать изображение"}</button>
      </form>
      <article className="content-panel studio-result">
        <Head eyebrow="Результат" title="Рабочий кадр" aside={generated ? "не сохранён" : "ожидает генерации"} />
        {generated ? <><Image src={generated} alt="Созданный визуал ArtHello" width={1024} height={1024} unoptimized /><div><a href={generated} download="arthello-generated.png">Скачать PNG</a><button onClick={() => { setGenerated(""); setPrompt(""); setReference(null); }}>Новый вариант</button></div></> : <div className="studio-placeholder"><span>AI</span><strong>Здесь появится готовый визуал</strong><small>Добавьте описание и, при желании, референс ArtHello. Без подключённого ключа система покажет инструкцию, а не фиктивный результат.</small></div>}
      </article>
    </div> : null}

    {activeTab === "plan" ? <article className="content-panel"><Head eyebrow="Редакционный ритм" title="Контент-план" aside={`${data.plan.length} материалов`} /><div className="plan-board">{["Черновик","На согласовании","Запланировано","Опубликовано"].map((status) => <section key={status}><header><strong>{status}</strong><span>{data.plan.filter((row) => row.status === status).length}</span></header>{data.plan.filter((row) => row.status === status).map((item) => <article key={item.id}><time>{date(item.scheduledAt)} · {data.accounts.find((row) => row.id === item.accountId)?.platform}</time><h3>{item.topic}</h3><p>{item.brief}</p><footer><span>{item.format} · {data.entityNames[item.authorEntityId]}</span>{item.status !== "Опубликовано" ? <button onClick={() => { setPublishId(item.id); setPublicationRef(""); }}>Опубликовать</button> : <em>{item.campaignId}</em>}</footer>{publishId === item.id ? <form onSubmit={(event) => { event.preventDefault(); void action({ action: "publishItem", planItemId: item.id, publicationRef }, `publish:${item.id}`).then((ok) => { if (ok) setPublishId(""); }); }}><input value={publicationRef} onChange={(event) => setPublicationRef(event.target.value)} placeholder="Ссылка или ID публикации" /><button disabled={busy === `publish:${item.id}`}>Подтвердить</button></form> : null}</article>)}</section>)}</div></article> : null}

    {activeTab === "publications" ? <div className="publication-grid">{data.publications.map((row) => <article key={row.id}><header><span>{row.account?.platform}</span><em>{row.id}</em></header><h2>{row.planItem?.topic}</h2><p>{row.planItem?.format} · {date(row.publishedAt)} · {row.publicationRef}</p><div className="publication-metrics"><span><small>Охват</small><strong>{number.format(row.reach)}</strong></span><span><small>Просмотры</small><strong>{number.format(row.views)}</strong></span><span><small>Реакции</small><strong>{number.format(row.reactions)}</strong></span><span><small>Переходы</small><strong>{number.format(row.clicks)}</strong><em>{row.rates.clickPercent}% CTR</em></span><span><small>Заявки</small><strong>{row.leads}</strong><em>{row.rates.leadPercent}%</em></span><span><small>Договоры</small><strong>{row.contracts}</strong></span></div><footer><strong>{row.revenueMinor ? rubles(row.revenueMinor) : "Нет выручки"}</strong><span>{row.dataQuality}</span></footer></article>)}</div> : null}

    {activeTab === "chain" ? <div className="content-chain">{data.chain.map((chain) => <article className="content-panel" key={chain.id}><Head eyebrow="Приёмочная атрибуция" title="Публикация → выручка" aside="CHAIN STATUS · PASS" /><div className="content-chain-steps">{[["Публикация", chain.publicationId, chain.planItem?.topic], ["Переход", chain.clickId, chain.attributionModel], ["Заявка", chain.leadId, chain.lead?.campaignId], ["Договор", chain.contractId, chain.lead?.offerId], ["Платёж", chain.paymentOperationId, chain.payment?.operationDate], ["Выручка", rubles(chain.revenueMinor), "Финансовый контур"]].map(([label, value, note], index) => <article key={label}><span>{index + 1}</span><small>{label}</small><strong>{value}</strong><em>{note}</em>{index < 5 ? <i>→</i> : null}</article>)}</div><div className="content-chain-actions"><p>{chain.payment?.dataQuality}</p><button onClick={onOpenSales}>Открыть заявку</button><button onClick={onOpenFinance}>Открыть финансы</button></div></article>)}</div> : null}

    {activeTab === "recommendations" ? <div className="recommendation-grid">{data.recommendations.map((row) => <article key={row.id}><header><span>{row.signalType}</span><em>{row.status}</em></header><h2>{row.recommendation}</h2><p>{row.evidence}</p><footer>{row.relatedTaskId ? <button onClick={onTasksChanged}>Задача TSK-{String(row.relatedTaskId).padStart(4,"0")}</button> : <button disabled={busy === row.id} onClick={() => void action({ action: "createRecommendationTask", recommendationId: row.id }, row.id)}>+ Задача на проверку</button>}<small>{row.publicationId}</small></footer></article>)}</div> : null}

    {createOpen ? <div className="content-modal-layer"><button className="drawer-scrim" onClick={() => setCreateOpen(false)} /><form className="content-modal" onSubmit={create}><header><div><p>Новый материал</p><h2>Добавить в контент-план</h2></div><button type="button" onClick={() => setCreateOpen(false)}>×</button></header><label><span>Дата и время</span><input type="datetime-local" name="scheduledAt" required /></label><div><label><span>Аккаунт</span><select name="accountId">{data.accounts.map((row) => <option key={row.id} value={row.id}>{row.platform}</option>)}</select></label><label><span>Автор</span><select name="authorEntityId"><option value="EMP-T-CONTENT-001">Редактор T-C01</option><option value="EMP-T-CONTENT-002">Автор T-C02</option></select></label></div><div><label><span>Формат</span><select name="format"><option>Пост</option><option>Карусель</option><option>Короткое видео</option><option>Видео</option><option>Лонгрид</option></select></label><label><span>Кампания</span><input name="campaignId" placeholder="CMP-T-…" /></label></div><label><span>Тема</span><input name="topic" required minLength={5} /></label><label><span>Бриф и бизнес-гипотеза</span><textarea name="brief" required minLength={10} /></label><input type="hidden" name="offerId" value="OFF-T-001" /><footer><button type="button" onClick={() => setCreateOpen(false)}>Отмена</button><button disabled={busy === "create"}>Сохранить план</button></footer></form></div> : null}
  </section>;
}

function Head({ eyebrow, title, aside }: { eyebrow: string; title: string; aside: string }) { return <header className="content-panel-head"><div><p>{eyebrow}</p><h2>{title}</h2></div><span>{aside}</span></header>; }
