"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import Image from "next/image";
import { createPortal } from "react-dom";
import { humanTechnicalText, recordLabel, taskRecordLabel } from "../../lib/record-labels";
import { Button, Card, EmptyState, KpiCard, PageContainer, PageHeader, Tabs } from "./design-system";
import "./ContentWorkspace.css";
import "./ContentWorkspace.ds.css";

type PlanItem = { id: string; scheduledAt: string; accountId: string; authorEntityId: string; format: string; topic: string; offerId: string; campaignId: string; status: string; brief: string };
type Publication = { id: string; planItemId: string; publishedAt: string; publicationRef: string; reach: number; views: number; reactions: number; clicks: number; leads: number; contracts: number; revenueMinor: number; dataQuality: string; rates: { engagementPercent: number; clickPercent: number; leadPercent: number; contractPercent: number }; planItem?: PlanItem; account?: { id: string; platform: string; displayName: string } };
type ContentData = {
  accounts: Array<{ id: string; platform: string; displayName: string; status: string; audienceCount: number; sourceType: string }>;
  plan: PlanItem[]; publications: Publication[];
  recommendations: Array<{ id: string; publicationId: string; signalType: string; evidence: string; recommendation: string; status: string; relatedTaskId: number | null }>;
  entityNames: Record<string, string>;
  summary: { reach: number; views: number; reactions: number; clicks: number; leads: number; contracts: number; revenueMinor: number };
  chain: Array<{ id: string; publicationId: string; clickId: string; leadId: string; contractId: string; paymentOperationId: string; revenueMinor: number; attributionModel: string; publication?: Publication; planItem?: PlanItem; lead?: { id: string; source: string; campaignId: string; offerId: string }; payment?: { id: string; amountMinor: number; operationDate: string; dataQuality: string } }>;
  sourcePolicy: { status: string; note: string; ranking: string };
};

type Tab = "overview" | "studio" | "plan" | "publications" | "chain" | "recommendations";
const tabs: Array<{ id: Tab; label: string }> = [{ id: "overview", label: "Обзор" }, { id: "studio", label: "Студия" }, { id: "plan", label: "Контент-план" }, { id: "publications", label: "Публикации" }, { id: "chain", label: "До выручки" }, { id: "recommendations", label: "Рекомендации" }];
const roleCodes: Record<string, string> = { "Собственник": "OWNER", "Директор": "DIRECTOR", "Маркетинг": "MARKETING", "Представитель Виталия": "REPRESENTATIVE", "Продажи": "SALES", "Финансы": "FINANCE", "Педагог": "TEACHER" };
const rub = new Intl.NumberFormat("ru-RU", { style: "currency", currency: "RUB", maximumFractionDigits: 0 });
const number = new Intl.NumberFormat("ru-RU");
const rubles = (minor: number) => rub.format(minor / 100);
const date = (value: string) => new Date(value).toLocaleDateString("ru-RU", { day: "2-digit", month: "short" });

export function ContentWorkspace({ role, notify, onTasksChanged, onOpenSales, onOpenFinance, onOpenIntegrations, sourceOnly = false }: { role: string; notify: (value: string) => void; onTasksChanged: () => void; onOpenSales: () => void; onOpenFinance: () => void; onOpenIntegrations: () => void; sourceOnly?: boolean }) {
  const [data, setData] = useState<ContentData | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [tab, setTab] = useState<Tab>("overview"); const [busy, setBusy] = useState(""); const [createOpen, setCreateOpen] = useState(false); const [publishId, setPublishId] = useState(""); const [publicationRef, setPublicationRef] = useState(""); const [prompt, setPrompt] = useState(""); const [reference, setReference] = useState<File | null>(null); const [generated, setGenerated] = useState(""); const [generationError, setGenerationError] = useState("");
  const [provider, setProvider] = useState("openai");
  const load = useCallback(async () => { try { const response = await fetch("/api/content", { cache: "no-store" }); const payload = await response.json() as ContentData & { error?: string }; if (!response.ok) throw new Error(payload.error ?? "Не удалось загрузить контент"); setData(payload); setError(""); } catch (loadError) { setError(loadError instanceof Error ? loadError.message : "Не удалось загрузить контент"); } finally { setLoading(false); } }, []);
  useEffect(() => { const handle = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(handle); }, [load]);
  async function action(body: Record<string, unknown>, key: string) { setBusy(key); try { const response = await fetch("/api/content-actions", { method: "POST", headers: { "content-type": "application/json", "x-arthello-role": roleCodes[role] ?? "" }, body: JSON.stringify(body) }); const payload = await response.json() as { error?: string; reused?: boolean }; if (!response.ok) throw new Error(payload.error ?? "Действие не выполнено"); notify(payload.reused ? "Связанная запись уже существует" : "Действие контента сохранено"); await load(); onTasksChanged(); return true; } catch (actionError) { notify(actionError instanceof Error ? actionError.message : "Действие не выполнено"); return false; } finally { setBusy(""); } }
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); if (await action({ action: "createPlanItem", ...Object.fromEntries(form.entries()) }, "create")) setCreateOpen(false); }
  async function generate(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy("generate"); setGenerationError(""); try { const form = new FormData(event.currentTarget); if (reference) form.set("reference", reference); const response = await fetch("/api/content-generate", { method: "POST", headers: { "x-arthello-role": roleCodes[role] ?? "", "x-csrf-token": readClientCookie("__Host-arthello_csrf") }, body: form }); const payload = await response.json() as { imageDataUrl?: string; error?: string; needsCredential?: boolean }; if (!response.ok || !payload.imageDataUrl) throw new Error(payload.error ?? "Изображение не создано"); setGenerated(payload.imageDataUrl); notify("Изображение создано. Оно не сохранено в базе — скачайте или добавьте в контент-план."); } catch (cause) { const message = cause instanceof Error ? cause.message : "Изображение не создано"; setGenerationError(message); notify(message); } finally { setBusy(""); } }
  const maxViews = useMemo(() => Math.max(1, ...(data?.publications.map((row) => row.views) ?? [])), [data]);
  const activeTab = sourceOnly ? "studio" : tab;
  if (loading) return <section className="ahContentStatus">Собираем контент до выручки…</section>;
  if (error || !data) return <PageContainer className="ahContentDenied"><Card><EmptyState title="Контур контента недоступен" description={error || "Не удалось получить подтверждённые данные контента."} density="compact" action={<Button onClick={() => void load()}>Повторить</Button>} /></Card></PageContainer>;
  const hasContentData = Boolean(data.accounts.length || data.plan.length || data.publications.length || data.chain.length || data.recommendations.length);
  const studioMode = sourceOnly || (!hasContentData && activeTab === "studio");
  return <PageContainer className="ahContentPage">
    <PageHeader eyebrow="КОНТЕНТ · КАНАЛЫ · ВЫРУЧКА" title="Контент и маркетинг" description={studioMode ? "Создавайте визуалы на основе описания и референсов. План и аналитика появятся после подключения выбранных каналов." : "План, публикации и метрики объединены с переходами, заявками, договорами и выручкой."} actions={studioMode ? <Button variant="primary" onClick={onOpenIntegrations}>Подключить ИИ</Button> : data.accounts.length ? <Button variant="primary" onClick={() => setCreateOpen(true)}>Добавить материал</Button> : <Button variant="primary" onClick={onOpenIntegrations}>Подключить источники</Button>} />
    <div className="ahContentBoundary"><strong>{studioMode ? "СТУДИЯ" : hasContentData ? "СОХРАНЁННЫЕ ДАННЫЕ" : "ДАННЫХ ПОКА НЕТ"}</strong><span>{studioMode ? "Результат появляется только после реального ответа подключённого провайдера." : hasContentData ? humanTechnicalText(data.sourcePolicy.note) : "Подключите социальные сети или добавьте первый материал после настройки аккаунта и ответственного."}</span><em>{studioMode ? "данные не сохраняются автоматически" : hasContentData ? humanTechnicalText(data.sourcePolicy.ranking) : "фиктивные показатели не показываются"}</em></div>
    <div className="ahContentKpis"><KpiCard label="Охват" value={number.format(data.summary.reach)} note={`${number.format(data.summary.views)} просмотров`} onClick={() => setTab("publications")} /><KpiCard label="Переходы" value={number.format(data.summary.clicks)} note={`${data.summary.views ? (data.summary.clicks / data.summary.views * 100).toFixed(1) : 0}% от просмотров`} onClick={() => setTab("publications")} /><KpiCard label="Заявки → договоры" value={`${data.summary.leads} → ${data.summary.contracts}`} note="по сохранённой атрибуции" onClick={() => setTab("chain")} /><KpiCard label="Выручка" value={rubles(data.summary.revenueMinor)} note="по связанным финансовым операциям" onClick={() => setTab("chain")} className={data.summary.revenueMinor ? "ahContentKpiPositive" : undefined} /></div>
    {!sourceOnly ? <div className="ahContentTabs"><Tabs items={tabs.map((item) => ({ id: item.id, label: item.id === "recommendations" ? <>{item.label}<b>{data.recommendations.filter((row) => row.status !== "Закрыта").length}</b></> : item.label }))} value={activeTab} onChange={setTab} ariaLabel="Разделы контента" /></div> : null}

    {activeTab === "overview" && !hasContentData ? <Card className="content-panel ahContentEmptyPanel"><Head eyebrow="Пустой контур" title="Контент ещё не подключён" aside="0 публикаций" /><EmptyState title="Каналов и материалов пока нет" description="До подключения источников охваты, лиды, договоры и выручка остаются пустыми." density="compact" action={<div className="ahContentEmptyActions"><Button onClick={() => setTab("studio")}>Открыть студию</Button><Button variant="primary" onClick={onOpenIntegrations}>Подключить источники</Button></div>} /></Card> : null}

    {activeTab === "overview" && hasContentData ? <div className="content-overview"><article className="content-panel"><Head eyebrow="Бизнес-результат" title="Публикации по доказанному эффекту" aside="выручка → договор → лид" /><div className="content-ranking">{data.publications.map((row, index) => <button key={row.id} onClick={() => setTab("publications")}><span>{String(index + 1).padStart(2, "0")}</span><div><strong>{humanTechnicalText(row.planItem?.topic || "Материал без названия")}</strong><small>{row.account?.platform} · {row.planItem?.format}</small><i><b style={{ width: `${Math.max(5, row.views / maxViews * 100)}%` }} /></i></div><em>{row.contracts ? `${row.contracts} договор` : `${row.leads} заявок`}</em><strong>{row.revenueMinor ? rubles(row.revenueMinor) : "—"}</strong></button>)}</div></article><article className="content-panel"><Head eyebrow="Каналы" title="Аккаунты" aside={`${data.accounts.length} контура`} /><div className="account-list">{data.accounts.map((account) => <article key={account.id}><span>{account.platform.slice(0,2).toUpperCase()}</span><div><strong>{account.displayName}</strong><small>{number.format(account.audienceCount)} аудитория</small></div><em>{account.status}</em></article>)}</div></article><article className="content-panel content-calendar"><Head eyebrow="Ближайшие материалы" title="Операционный план" aside="авторы назначены" /><div>{data.plan.slice(-3).map((item) => <article key={item.id}><time>{date(item.scheduledAt)}</time><span><strong>{humanTechnicalText(item.topic)}</strong><small>{data.accounts.find((row) => row.id === item.accountId)?.platform} · {item.format} · {data.entityNames[item.authorEntityId] || "Автор не назначен"}</small></span><em>{item.status}</em></article>)}</div></article></div> : null}
    {activeTab === "overview" && hasContentData ? <ContentAnalysis data={data} openPublications={() => setTab("publications")} /> : null}

    {activeTab === "studio" ? <div className="content-studio" aria-label="Студия создания изображений">
      <form className="ahCard content-panel studio-form" onSubmit={generate}>
        <Head eyebrow="Генерация по подключению" title="Создать изображение" aside="модель + запрос + референс" />
        <label><span>Модель изображений</span><select name="provider" value={provider} onChange={(event)=>setProvider(event.target.value)}><option value="openai">OpenAI Images</option><option value="google">Google Gemini · подключить ключ</option><option value="recraft">Recraft · подключить ключ</option></select><small>Выберите подключённую модель. Результат приходит только от настроенного сервиса.</small></label>
        <label><span>Что нужно создать</span><textarea name="prompt" value={prompt} onChange={(event) => setPrompt(event.target.value)} minLength={12} required placeholder="Например: спокойная предметная фотография учебной мастерской ArtHello, белый фон, чёрные детали, один красный акцент…" /></label>
        <div><label><span>Формат</span><select name="size" defaultValue="1024x1024"><option value="1024x1024">Квадрат 1:1</option><option value="1536x1024">Горизонтальный 3:2</option><option value="1024x1536">Вертикальный 2:3</option></select></label><label><span>Качество</span><select name="quality" defaultValue="medium"><option value="low">Черновик</option><option value="medium">Стандарт</option><option value="high">Высокое</option></select></label></div>
        <label className="reference-upload"><span>Референс ArtHello — необязательно</span><input type="file" accept="image/png,image/jpeg,image/webp" onChange={(event) => setReference(event.target.files?.[0] ?? null)} /><small>{reference ? `${reference.name} · ${(reference.size / 1024 / 1024).toFixed(1)} МБ` : "PNG, JPEG или WebP до 8 МБ"}</small></label>
        <div className="studio-privacy"><strong>Контроль данных</strong><span>Картинка отправляется в OpenAI только после нажатия. ArtHello OS не хранит референс и результат в текущей версии.</span></div>
        {generationError ? <div className="studio-error"><strong>Генерация пока недоступна</strong><span>{generationError}</span><small>Подключите выбранный ИИ в Центре интеграций и добавьте ключ в защищённые переменные рабочего контура.</small></div> : null}
        <Button type="submit" variant="primary" disabled={busy === "generate"}>{busy === "generate" ? "Создаём изображение…" : "Создать изображение"}</Button>
      </form>
      <article className="ahCard content-panel studio-result">
        <Head eyebrow="Результат" title="Рабочий кадр" aside={generated ? "не сохранён" : "ожидает генерации"} />
        {generated ? <><Image src={generated} alt="Созданный визуал ArtHello" width={1024} height={1024} unoptimized /><div><a href={generated} download="arthello-generated.png">Скачать PNG</a><Button variant="secondary" onClick={() => { setGenerated(""); setPrompt(""); setReference(null); }}>Новый вариант</Button></div></> : <div data-ah-compact-card="true" className="studio-placeholder"><span aria-hidden="true">✦</span><strong>Здесь появится готовый визуал</strong><small>Добавьте описание и, при желании, референс ArtHello. Без подключённого ключа система покажет инструкцию, а не фиктивный результат.</small></div>}
      </article>
    </div> : null}

    {activeTab === "plan" ? data.plan.length ? <article className="content-panel"><Head eyebrow="Редакционный ритм" title="Контент-план" aside={`${data.plan.length} материалов`} /><div className="plan-board">{["Черновик","На согласовании","Запланировано","Опубликовано"].map((status) => <section key={status}><header><strong>{status}</strong><span>{data.plan.filter((row) => row.status === status).length}</span></header>{data.plan.filter((row) => row.status === status).map((item) => <article key={item.id}><time>{date(item.scheduledAt)} · {data.accounts.find((row) => row.id === item.accountId)?.platform}</time><h3>{humanTechnicalText(item.topic)}</h3><p>{humanTechnicalText(item.brief)}</p><footer><span>{item.format} · {data.entityNames[item.authorEntityId] || "Автор не назначен"}</span>{item.status !== "Опубликовано" ? <button onClick={() => { setPublishId(item.id); setPublicationRef(""); }}>Опубликовать</button> : <em>{recordLabel("Материал", item.id)}</em>}</footer>{publishId === item.id ? <form onSubmit={(event) => { event.preventDefault(); void action({ action: "publishItem", planItemId: item.id, publicationRef }, `publish:${item.id}`).then((ok) => { if (ok) setPublishId(""); }); }}><input value={publicationRef} onChange={(event) => setPublicationRef(event.target.value)} placeholder="Ссылка на публикацию" /><button disabled={busy === `publish:${item.id}`}>Подтвердить</button></form> : null}</article>)}</section>)}</div></article> : <Card className="content-panel"><EmptyState title="Контент-план пока пуст" description="Материал появится после выбора канала, автора, даты и бизнес-гипотезы." density="compact" action={<Button variant="primary" onClick={data.accounts.length ? () => setCreateOpen(true) : onOpenIntegrations}>{data.accounts.length ? "Добавить материал" : "Подключить канал"}</Button>} /></Card> : null}

    {activeTab === "publications" ? data.publications.length ? <div className="publication-grid">{data.publications.map((row) => <article key={row.id}><header><span>{row.account?.platform}</span><em>{recordLabel("Публикация", row.id)}</em></header><h2>{humanTechnicalText(row.planItem?.topic || "Материал без названия")}</h2><p>{row.planItem?.format} · {date(row.publishedAt)} · ссылка на публикацию сохранена</p><div className="publication-metrics"><span><small>Охват</small><strong>{number.format(row.reach)}</strong></span><span><small>Просмотры</small><strong>{number.format(row.views)}</strong></span><span><small>Реакции</small><strong>{number.format(row.reactions)}</strong></span><span><small>Переходы</small><strong>{number.format(row.clicks)}</strong><em>{row.rates.clickPercent}% от просмотров</em></span><span><small>Заявки</small><strong>{row.leads}</strong><em>{row.rates.leadPercent}%</em></span><span><small>Договоры</small><strong>{row.contracts}</strong></span></div><footer><strong>{row.revenueMinor ? rubles(row.revenueMinor) : "Нет выручки"}</strong><span>{humanTechnicalText(row.dataQuality)}</span></footer></article>)}</div> : <Card className="content-panel"><EmptyState title="Публикаций пока нет" description="Статистика появится только после сохранённой публикации и ответа подключённого канала." density="compact" /></Card> : null}

    {activeTab === "chain" ? data.chain.length ? <div className="content-chain">{data.chain.map((chain) => { const paymentQuality = chain.payment?.dataQuality ? humanTechnicalText(chain.payment.dataQuality) : "источник не указан"; return <article className="content-panel" key={chain.id}><Head eyebrow="Атрибуция по сохранённым данным" title="Публикация → выручка" aside={paymentQuality} /><div className="content-chain-steps">{[["Публикация", recordLabel("Публикация", chain.publicationId), chain.planItem?.topic], ["Переход", recordLabel("Переход", chain.clickId), "Подтверждённый переход"], ["Заявка", recordLabel("Заявка", chain.leadId), "Связана с публикацией"], ["Договор", recordLabel("Договор", chain.contractId), "Связан с заявкой"], ["Платёж", recordLabel("Операция", chain.paymentOperationId), chain.payment?.operationDate], ["Выручка", rubles(chain.revenueMinor), "Финансовый контур"]].map(([label, value, note], index) => <article key={label}><span>{index + 1}</span><small>{label}</small><strong>{value}</strong><em>{note}</em>{index < 5 ? <i>→</i> : null}</article>)}</div><div className="content-chain-actions"><p>{paymentQuality}</p><button onClick={onOpenSales}>Открыть заявку</button><button onClick={onOpenFinance}>Открыть финансы</button></div></article>; })}</div> : <Card className="content-panel"><EmptyState title="Сквозная цепочка пока не собрана" description="Связь появится после подтверждённых перехода, заявки, договора и финансовой операции." density="compact" /></Card> : null}

    {activeTab === "recommendations" ? data.recommendations.length ? <div className="recommendation-grid">{data.recommendations.map((row) => <article key={row.id}><header><span>{row.signalType}</span><em>{row.status}</em></header><h2>{humanTechnicalText(row.recommendation)}</h2><p>{humanTechnicalText(row.evidence)}</p><footer>{row.relatedTaskId ? <button onClick={onTasksChanged}>{taskRecordLabel(row.relatedTaskId)}</button> : <button disabled={busy === row.id} onClick={() => void action({ action: "createRecommendationTask", recommendationId: row.id }, row.id)}>+ Задача на проверку</button>}<small>{recordLabel("Публикация", row.publicationId)}</small></footer></article>)}</div> : <Card className="content-panel"><EmptyState title="Рекомендаций пока нет" description="Сигнал появится только вместе с доказательством, публикацией и ответственным за проверку." density="compact" /></Card> : null}

    {createOpen ? createPortal(<div className="content-modal-layer"><button className="drawer-scrim" onClick={() => setCreateOpen(false)} /><form className="content-modal" onSubmit={create}><header><div><p>Новый материал</p><h2>Добавить в контент-план</h2></div><button type="button" onClick={() => setCreateOpen(false)}>×</button></header><label><span>Дата и время</span><input type="datetime-local" name="scheduledAt" required /></label><div><label><span>Аккаунт</span><select name="accountId" required>{data.accounts.map((row) => <option key={row.id} value={row.id}>{row.platform}</option>)}</select></label><label><span>Автор</span><select name="authorEntityId" required><option value="">Выберите автора</option>{Object.entries(data.entityNames).map(([id, name]) => <option key={id} value={id}>{name}</option>)}</select></label></div><div><label><span>Формат</span><select name="format"><option>Пост</option><option>Карусель</option><option>Короткое видео</option><option>Видео</option><option>Лонгрид</option></select></label><label><span>Кампания</span><input name="campaignId" placeholder="Название кампании" /></label></div><label><span>Тема</span><input name="topic" required minLength={5} /></label><label><span>Бриф и бизнес-гипотеза</span><textarea name="brief" required minLength={10} /></label><input type="hidden" name="offerId" value="" /><footer><button type="button" onClick={() => setCreateOpen(false)}>Отмена</button><button disabled={busy === "create"}>Сохранить план</button></footer></form></div>, document.body) : null}
  </PageContainer>;
}

function Head({ eyebrow, title, aside }: { eyebrow: string; title: string; aside: string }) { return <header className="content-panel-head"><div><p>{eyebrow}</p><h2>{title}</h2></div><span>{aside}</span></header>; }

function ContentAnalysis({data,openPublications}:{data:ContentData;openPublications:()=>void}){
  const channelRows=data.accounts.map(account=>{const rows=data.publications.filter(row=>row.account?.id===account.id);return{...account,posts:rows.length,reach:rows.reduce((sum,row)=>sum+row.reach,0),views:rows.reduce((sum,row)=>sum+row.views,0),reactions:rows.reduce((sum,row)=>sum+row.reactions,0),clicks:rows.reduce((sum,row)=>sum+row.clicks,0)}}),posts=data.publications.filter(row=>!/(короткое видео|stories|reels|истори)/i.test(row.planItem?.format||"")),stories=data.publications.filter(row=>/(короткое видео|stories|reels|истори)/i.test(row.planItem?.format||"")),topPost=[...posts].sort((a,b)=>b.views-a.views)[0],topStory=[...stories].sort((a,b)=>b.views-a.views)[0],engagement=data.summary.reach?data.summary.reactions/data.summary.reach*100:0,ctr=data.summary.views?data.summary.clicks/data.summary.views*100:0,leadRate=data.summary.clicks?data.summary.leads/data.summary.clicks*100:0;
  return <div className="content-analysis"><article className="content-panel"><Head eyebrow="Все социальные сети" title="Статистика каналов" aside="единый срез"/><div className="channel-scoreboard"><div><span>Канал</span><span>Материалы</span><span>Охват</span><span>Просмотры</span><span>Реакции</span><span>Переходы</span></div>{channelRows.map(row=><button key={row.id} onClick={openPublications}><strong>{row.platform}</strong><span>{row.posts}</span><span>{number.format(row.reach)}</span><span>{number.format(row.views)}</span><span>{number.format(row.reactions)}</span><span>{number.format(row.clicks)}</span></button>)}</div></article><article className="content-panel content-best"><Head eyebrow="Лучшие материалы" title="Посты и короткие видео" aside="по просмотрам"/><div><Best label="Лучший пост" row={topPost}/><Best label="Лучшее короткое видео" row={topStory}/></div></article><article className="content-panel content-evaluation"><Head eyebrow="Оценка деятельности" title="Что работает" aside="без автоматических решений"/><div><span><small>Вовлечённость</small><strong>{engagement.toFixed(1)}%</strong></span><span><small>Доля переходов</small><strong>{ctr.toFixed(1)}%</strong></span><span><small>Заявки из переходов</small><strong>{leadRate.toFixed(1)}%</strong></span><span><small>Договоры</small><strong>{data.summary.contracts}</strong></span></div><p>{data.summary.contracts?"Есть публикация с подтверждённым переходом до договора и выручки. Масштабирование — только после проверки реальных метрик источника и атрибуции.":"Пока нет подтверждённой связи с договором. Оцениваем темы и каналы по переходам и заявкам, а не только по охвату."}</p></article></div>
}

function Best({label,row}:{label:string;row?:Publication}){return <button disabled={!row}><span>{label}</span><strong>{row ? humanTechnicalText(row.planItem?.topic || "Материал без названия") : "Пока нет публикаций этого формата"}</strong><small>{row?`${row.account?.platform} · ${number.format(row.views)} просмотров · ${number.format(row.reactions)} реакций`:"Появится после подключения канала"}</small></button>}

function readClientCookie(name: string) {
  const prefix = `${name}=`;
  const item = document.cookie.split(";").map((part) => part.trim()).find((part) => part.startsWith(prefix));
  if (!item) return "";
  try {
    return decodeURIComponent(item.slice(prefix.length));
  } catch {
    return "";
  }
}
