"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { createPortal } from "react-dom";
import { humanPeriodLabel, humanTechnicalText, recordLabel, recordNumber } from "../../lib/record-labels";
import { Button, Card, EmptyState, KpiCard, PageContainer, PageHeader, Tabs } from "./design-system";
import { SoftSelect } from "./SoftSelect";
import "./DirectoryWorkspace.css";
import "./HrWorkspace.ds.css";

type Employee = { id:string; candidateId:string; contractId:string; positionId:string; unit:string; rateMinor:number; hireDate:string; status:string; terminationDate:string; terminationReason:string; accessStatus:string };
type EmployeeProfile = { contact?:string; employmentType?:string; note?:string; branches?:string[]; branchIds?:string[]; sourceSystem?:string; dataQuality?:string };
type Branch={id:string;name:string;kind:string;status:string};
type Data={vacancies:Array<{id:string;title:string;unit:string;headcount:number;status:string}>;candidates:Array<{id:string;entityId:string;vacancyId:string;source:string;stage:string;score:number;decision:string;rejectionReason:string;offerStatus:string;evidence:string}>;interviews:Array<{id:string;candidateId:string;scheduledAt:string;score:number;summary:string;decision:string}>;employees:Employee[];onboarding:Array<{id:string;employeeId:string;step:string;status:string;dueDate:string;evidence:string;relatedTaskId:number|null}>;development:Array<{id:string;employeeId:string;eventType:string;title:string;eventDate:string;score:number;status:string;evidence:string}>;rewards:Array<{id:string;employeeId:string;eventType:string;amountMinor:number;reason:string;period:string;status:string}>;accesses:Array<{id:string;employeeId:string;system:string;role:string;status:string;grantedAt:string;revokedAt:string;revocationReason:string}>;entityNames:Record<string,string>;employeeProfiles:Record<string,EmployeeProfile>;branches:Branch[];documents:Array<{id:string;title:string;status:string}>;tasks:Array<{id:number;sourceId:string;status:string;result:string}>;payroll:Array<{id:string;counterpartyEntityId:string;amountMinor:number;period:string;dataQuality:string}>;funnel:Array<{stage:string;count:number}>;summary:{openVacancies:number;candidates:number;activeEmployees:number;revokedAccesses:number};chain:{vacancyId:string;candidateId:string;interviewId:string;employeeId:string;contractId:string;positionId:string;accessId:string;onboardingId:string;payrollId:string;evaluationId:string};boundary:string};
const roleCodes:Record<string,string>={"Собственник":"OWNER","Директор":"DIRECTOR","Представитель Виталия":"REPRESENTATIVE","HR":"HR","Финансы":"FINANCE","Продажи":"SALES","Маркетинг":"MARKETING","Педагог":"TEACHER","Методист":"METHODIST","Родитель":"PARENT"};
const tabs=["Обзор","Найм","Сотрудники","Развитие","Увольнение"] as const;
type Tab=typeof tabs[number];
type StaffDialog={kind:"create"}|{kind:"edit";employee:Employee}|{kind:"import"};
const rub=(minor:number)=>new Intl.NumberFormat("ru-RU",{style:"currency",currency:"RUB",maximumFractionDigits:0}).format(minor/100);
const humanPosition=(value:string)=>{
  const position=value.trim();
  if(!position)return "Должность не указана";
  if(!/^POS(?:-|_|:)/i.test(position))return position;
  const code=position.toUpperCase();
  if(code.includes("TEACHER"))return "Педагог";
  if(code.includes("CURATOR"))return "Куратор класса";
  if(code.includes("METHODIST"))return "Методист";
  return "Должность из кадровой карточки";
};

export function HrWorkspace({role,notify,onTasksChanged,onOpenDocuments}:{role:string;notify:(v:string)=>void;onTasksChanged:()=>void;onOpenDocuments:(focusId:string)=>void}){
  const[data,setData]=useState<Data|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[tab,setTab]=useState<Tab>("Обзор"),[busy,setBusy]=useState(""),[dialog,setDialog]=useState<StaffDialog|null>(null),[lifecycleEmployeeId,setLifecycleEmployeeId]=useState("");
  const load=useCallback(async()=>{setLoading(true);try{const r=await fetch("/api/hr",{cache:"no-store",headers:{"x-arthello-role":roleCodes[role]??""}}),p=await r.json() as Data&{error?:string};if(!r.ok)throw new Error(p.error??"Ошибка");setData(p);setError("")}catch(e){setData(null);setError(e instanceof Error?e.message:"Нет доступа")}finally{setLoading(false)}},[role]);
  useEffect(()=>{const id=setTimeout(()=>void load(),0);return()=>clearTimeout(id)},[load]);
  async function action(body:Record<string,unknown>,key:string){setBusy(key);try{const r=await fetch("/api/hr-actions",{method:"POST",headers:{"content-type":"application/json","x-arthello-role":roleCodes[role]??""},body:JSON.stringify(body)}),p=await r.json() as{error?:string;reused?:boolean;created?:number;rejected?:Array<unknown>};if(!r.ok)throw new Error(p.error??"Ошибка");notify(p.created!==undefined?`Добавлено сотрудников: ${p.created}${p.rejected?.length?` · требуют проверки: ${p.rejected.length}`:""}`:p.reused?"Запись уже существует":"Изменения сохранены");await load();onTasksChanged();return true}catch(e){notify(e instanceof Error?e.message:"Ошибка");return false}finally{setBusy("")}}
  if(loading)return <section className="ahHrStatus">Загружаем контур команды…</section>;if(error||!data)return <PageContainer className="ahHrDenied"><Card><EmptyState title="Контур команды недоступен" description={error||"Данные команды доступны только кадровой службе, руководителям и представителю собственника."} density="compact" action={<Button onClick={()=>void load()}>Повторить</Button>}/></Card></PageContainer>;
  const chainEmployee=data.employees.find(x=>x.id===lifecycleEmployeeId),chainCandidate=chainEmployee?data.candidates.find(x=>x.id===chainEmployee.candidateId):undefined,chainVacancy=chainCandidate?data.vacancies.find(x=>x.id===chainCandidate.vacancyId):undefined,chainInterview=chainCandidate?data.interviews.find(x=>x.candidateId===chainCandidate.id):undefined,chainAccess=chainEmployee?data.accesses.find(x=>x.employeeId===chainEmployee.id):undefined,chainOnboarding=chainEmployee?data.onboarding.find(x=>x.employeeId===chainEmployee.id):undefined,chainPayroll=chainEmployee?data.payroll.find(x=>x.counterpartyEntityId===chainEmployee.id):undefined,chainEvaluation=chainEmployee?data.development.find(x=>x.employeeId===chainEmployee.id):undefined,activeEmployees=data.employees.filter(x=>x.status==="Работает");
  return <PageContainer className="ahHrPage">
    <PageHeader eyebrow="КОМАНДА · ИСТОЧНИКИ · ДОСТУПЫ" title="Команда" description="Единый реестр персонала: ручное добавление, контролируемый импорт, кадровая история и отдельная выдача доступов." actions={<div className="ahHrHeaderActions"><Button onClick={()=>setDialog({kind:"import"})}>Импортировать</Button><Button variant="primary" onClick={()=>setDialog({kind:"create"})}>Добавить сотрудника</Button></div>}/>
    <div className="ahHrBoundary"><strong>КАДРОВЫЙ КОНТУР</strong><span>{data.boundary}</span></div>
    <div className="ahHrKpis"><KpiCard label="Вакансии в работе" value={data.summary.openVacancies} note={`${data.summary.candidates} кандидатов в реестре`} onClick={()=>setTab("Найм")}/><KpiCard label="Работают" value={data.summary.activeEmployees} note="источник списка пользователей" onClick={()=>setTab("Сотрудники")}/><KpiCard label="События развития" value={data.development.length} note="обучение, оценка, резерв" onClick={()=>setTab("Развитие")}/><KpiCard label="Отозвано доступов" value={data.summary.revokedAccesses} note="история действий сохранена" onClick={()=>setTab("Увольнение")} className={data.summary.revokedAccesses?"ahHrKpiWarning":undefined}/></div>
    <div className="ahHrTabs"><Tabs items={tabs.map(x=>({id:x,label:x}))} value={tab} onChange={setTab} ariaLabel="Разделы команды"/></div>
    {tab==="Обзор"?<div className="hr-layout"><article className="hr-panel hr-chain"><Head p="Путь сотрудника" h="Жизненный цикл сотрудника" s={chainEmployee?"связанные этапы":"выберите сотрудника"}/><label className="hr-lifecycle-picker"><span>Чей путь показать</span><SoftSelect name="lifecycleEmployee" ariaLabel="Сотрудник для просмотра жизненного цикла" value={lifecycleEmployeeId} onChange={setLifecycleEmployeeId} options={[{value:"",label:"Выберите сотрудника"},...data.employees.map(employee=>({value:employee.id,label:data.entityNames[employee.id]??recordLabel("Сотрудник",employee.id)}))]}/><small>Сотрудник не выбирается автоматически: здесь показывается только тот, кого вы указали.</small></label>{chainEmployee?<div>{[["Вакансия",chainVacancy?.title||"Не связана",chainVacancy?.status||""],["Кандидат",chainCandidate?data.entityNames[chainCandidate.entityId]||recordLabel("Кандидат",chainCandidate.id):"Не связан",chainCandidate?.source||""],["Интервью",chainInterview?recordLabel("Интервью",chainInterview.id):"Не проведено",chainInterview?.decision||""],["Сотрудник",data.entityNames[chainEmployee.id]||recordLabel("Сотрудник",chainEmployee.id),chainEmployee.status],["Договор",chainEmployee.contractId?recordLabel("Договор",chainEmployee.contractId):"Не привязан","Трудовой"],["Должность и ставка",humanPosition(chainEmployee.positionId),rub(chainEmployee.rateMinor)],["Доступы",chainAccess?chainAccess.system:"Не выдавались",chainEmployee.accessStatus],["Задачи и обучение",chainOnboarding?.step||"Не назначены",chainOnboarding?.status||""],["Зарплата",chainPayroll?rub(chainPayroll.amountMinor):"Начислений нет",chainPayroll?.period?humanPeriodLabel(chainPayroll.period):""],["Оценка",chainEvaluation?.title||"Не проводилась",chainEvaluation?.status||""],["Увольнение",chainEmployee.terminationDate||"Не оформлено",chainEmployee.terminationReason||""]].map(([a,b,c],i)=><article key={String(a)}><span>{i+1}</span><div><small>{a}</small><strong>{b}</strong><em>{c}</em></div></article>)}</div>:<EmptyState title="Выберите сотрудника" description="Мы соберём его путь от вакансии и найма до доступов, обучения, выплат и увольнения." density="compact"/>}</article><article className="hr-panel"><Head p="Воронка" h="Найм по этапам" s={data.funnel.length?"без скачков":"данных пока нет"}/>{data.funnel.length?<div className="funnel-bars">{data.funnel.map((x,i)=><div key={x.stage}><span>{x.stage}</span><i style={{width:`${Math.max(12,x.count/Math.max(1,data.summary.candidates)*100)}%`}}/><strong>{x.count}</strong><small>{i<data.funnel.length-1?"следующий контрольный этап":"оформлен"}</small></div>)}</div>:<EmptyState title="Вакансий и кандидатов пока нет" description="Создайте кадровую потребность или добавьте подтверждённого кандидата." density="compact"/>}</article></div>:null}
    {tab==="Найм"?<div className="hr-layout"><article className="hr-panel"><Head p="Вакансии" h="Потребность и статус" s={`${data.vacancies.length} карточки`}/><div className="vacancy-list">{data.vacancies.map(x=><article key={x.id}><span>{recordLabel("Вакансия",x.id)}</span><div><strong>{x.title}</strong><small>{x.unit} · {x.headcount} ставка</small></div><em>{x.status}</em></article>)}</div></article><article className="hr-panel"><Head p="Кандидаты" h="Воронка и решения" s="оценка с доказательством"/><div className="candidate-list">{data.candidates.map(x=>{const vacancy=data.vacancies.find(v=>v.id===x.vacancyId);return <article key={x.id}><header><strong>{data.entityNames[x.entityId]||recordLabel("Кандидат",x.id)}</strong><span>{x.score}/100</span><em>{x.stage}</em></header><p>{x.source} · {vacancy?.title||recordLabel("Вакансия",x.vacancyId)}</p><small>{humanHrEvidence(x.evidence)}</small>{x.rejectionReason?<div className="reason">Отсев: {x.rejectionReason}</div>:null}{x.stage==="Интервью"?<button disabled={busy===x.id} onClick={()=>void action({action:"advanceCandidate",candidateId:x.id,targetStage:"Решение",evidence:"Интервью проведено, матрица и кейс проверены"},x.id)}>На решение</button>:null}</article>})}</div></article></div>:null}
    {tab==="Сотрудники"?<><div className="staff-source-note"><strong>Единый источник персонала</strong><span>Сотрудник создаётся здесь один раз. После сохранения он автоматически появляется в «Настройки → Доступы», но доступ остаётся невыданным до отдельного подтверждения.</span><div><button onClick={()=>setDialog({kind:"import"})}>Импорт CSV / из Excel</button><button onClick={()=>setDialog({kind:"create"})}>+ Добавить вручную</button></div></div><div className="employee-grid">{data.employees.map(x=>{const profile=data.employeeProfiles[x.id]??{};return <article key={x.id}><header><div><span>{recordLabel("Сотрудник",x.id)}</span><h2>{data.entityNames[x.id]??recordLabel("Сотрудник",x.id)}</h2></div><em className={x.status==="Уволен"?"closed":""}>{x.status}</em></header><dl><div><dt>Филиалы</dt><dd>{profile.branches?.join(", ")||x.unit||"Не назначены"}</dd></div><div><dt>Должность</dt><dd>{humanPosition(x.positionId)}</dd></div><div><dt>Контакт</dt><dd>{profile.contact||"Не указан"}</dd></div><div><dt>Ставка</dt><dd>{rub(x.rateMinor)}</dd></div><div><dt>Дата приёма</dt><dd>{x.hireDate}</dd></div><div><dt>Доступы</dt><dd>{x.accessStatus}</dd></div>{x.contractId?<div><dt>Договор</dt><dd><button className="employee-contract-link" onClick={()=>onOpenDocuments(x.contractId)}>{recordLabel("Договор",x.contractId)} →</button></dd></div>:null}</dl><div className="employee-actions"><button className="secondary" onClick={()=>setDialog({kind:"edit",employee:x})}>Редактировать</button>{x.status==="Работает"?<button disabled={busy===x.id} onClick={()=>void action({action:"createOnboardingTask",employeeId:x.id},x.id)}>+ Задача адаптации</button>:null}</div>{x.status==="Уволен"?<footer>Уволен {x.terminationDate} · история не удалена</footer>:<small className="employee-source">{profile.sourceSystem==="CSV_IMPORT"?"Импорт · требуется проверка":profile.sourceSystem==="MANUAL"?"Ручной ввод":"Источник не указан"}</small>}</article>})}</div></>:null}
    {tab==="Развитие"?<div className="hr-layout"><article className="hr-panel"><Head p="Развитие" h="Обучение, аттестации и резерв" s="проверяемые сигналы"/><div className="development-list">{data.development.map(x=><article key={x.id}><span>{x.score}</span><div><small>{x.eventType} · {x.eventDate}</small><strong>{x.title}</strong><p>{humanHrEvidence(x.evidence)}</p></div><em>{x.status}</em></article>)}</div></article><article className="hr-panel"><Head p="Решения по мотивации" h="Премии, депремирование, нарушения" s="только по заполненному основанию"/><div className="reward-list">{data.rewards.map(x=><article key={x.id}><header><strong>{x.eventType}</strong><em>{x.status}</em></header><p>{x.reason}</p><footer>{humanPeriodLabel(x.period)}<span>{x.amountMinor?rub(x.amountMinor):"без денежного события"}</span></footer></article>)}</div>{activeEmployees.length?<PersonnelEventForm employees={activeEmployees} entityNames={data.entityNames} busy={busy} submit={body=>action({...body,action:"recordPersonnelEvent"},"personnel-event")}/>:<p className="empty-inline">Нет работающих сотрудников для кадрового события.</p>}</article></div>:null}
    {tab==="Увольнение"?<div className="hr-layout"><article className="hr-panel"><Head p="Завершение работы" h="Увольнение и отзыв доступов" s="только после заполнения основания"/>{data.employees.some(employee=>employee.status==="Уволен")?<div className="offboarding-proof">{data.employees.filter(employee=>employee.status==="Уволен").slice(0,1).map(employee=><div key={employee.id}><span>{recordLabel("Сотрудник",employee.id)}</span><strong>{data.entityNames[employee.id]||"Сотрудник"}</strong><small>уволен {employee.terminationDate}</small></div>)}</div>:<p className="empty-inline">Завершённых увольнений пока нет.</p>}{activeEmployees.length?<TerminationForm employees={activeEmployees} entityNames={data.entityNames} busy={busy} submit={body=>action({...body,action:"terminateEmployee"},"terminate-employee")}/>:<p className="empty-inline">Нет работающих сотрудников для завершения увольнения.</p>}</article><article className="hr-panel"><Head p="Доступы" h="Активные и отозванные" s={`${data.accesses.length} записи`}/>{data.accesses.length?<div className="access-list">{data.accesses.map(x=><article key={x.id}><span>{x.status==="Активен"?"●":"×"}</span><div><strong>{x.system}</strong><small>{data.entityNames[x.employeeId]||recordLabel("Сотрудник",x.employeeId)} · {roleLabel(x.role)}</small></div><em>{x.status}</em><small>{x.revokedAt||x.grantedAt}</small></article>)}</div>:<p className="empty-inline">Истории отзывов доступа пока нет.</p>}</article></div>:null}
    {dialog?.kind==="create"?<EmployeeModal displayName="" employee={null} profile={{}} branches={data.branches} busy={busy} close={()=>setDialog(null)} onOpenDocuments={onOpenDocuments} submit={async body=>{const ok=await action({...body,action:"createEmployee"},"save-employee");if(ok){setDialog(null);setTab("Сотрудники")}}}/>:null}
    {dialog?.kind==="edit"?<EmployeeModal displayName={data.entityNames[dialog.employee.id]??""} employee={dialog.employee} profile={data.employeeProfiles[dialog.employee.id]??{}} branches={data.branches} busy={busy} close={()=>setDialog(null)} onOpenDocuments={onOpenDocuments} submit={async body=>{const ok=await action({...body,action:"updateEmployee",employeeId:dialog.employee.id},"save-employee");if(ok)setDialog(null)}}/>:null}
    {dialog?.kind==="import"?<ImportEmployeesModal busy={busy} close={()=>setDialog(null)} submit={async rows=>{const prepared=rows.map(row=>withBranchCatalog(row,data.branches));const ok=await action({action:"importEmployees",rows:prepared},"import-employees");if(ok){setDialog(null);setTab("Сотрудники")}}}/>:null}
  </PageContainer>
}

function PersonnelEventForm({employees,entityNames,busy,submit}:{employees:Employee[];entityNames:Record<string,string>;busy:string;submit:(body:Record<string,unknown>)=>Promise<boolean>}){
  const[employeeId,setEmployeeId]=useState("");
  async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!employeeId)return;const formElement=event.currentTarget,form=new FormData(formElement),amountRubles=Number(form.get("amountRubles")??0);if(await submit({employeeId,eventType:String(form.get("eventType")??""),amountMinor:Math.round(amountRubles*100),reason:String(form.get("reason")??"")})){formElement.reset();setEmployeeId("")}}
  return <form className="access-separation" onSubmit={save}><strong>Добавить кадровое событие</strong><span>Выберите сотрудника и укажите фактическую сумму и проверяемое основание.</span><label><span>Сотрудник</span><SoftSelect name="employeeId" ariaLabel="Сотрудник для кадрового события" value={employeeId} onChange={setEmployeeId} options={[{value:"",label:"Выберите сотрудника"},...employees.map(employee=>({value:employee.id,label:entityNames[employee.id]??recordLabel("Сотрудник",employee.id)}))]}/></label><label><span>Тип события</span><SoftSelect name="eventType" ariaLabel="Тип кадрового события" defaultValue="Премия" options={["Премия","Депремирование","Нарушение"].map(value=>({value,label:value}))}/></label><label><span>Сумма, ₽</span><input name="amountRubles" type="number" min="0" step="0.01" required placeholder="Введите фактическую сумму"/></label><label><span>Основание</span><textarea name="reason" required minLength={8} placeholder="Документ, результат или иное проверяемое основание"/></label><button disabled={!employeeId||busy==="personnel-event"}>{busy==="personnel-event"?"Сохраняем…":"Сохранить на согласование"}</button></form>
}

function TerminationForm({employees,entityNames,busy,submit}:{employees:Employee[];entityNames:Record<string,string>;busy:string;submit:(body:Record<string,unknown>)=>Promise<boolean>}){
  const[employeeId,setEmployeeId]=useState("");
  async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!employeeId)return;const formElement=event.currentTarget,form=new FormData(formElement);if(await submit({employeeId,reason:String(form.get("reason")??"")})){formElement.reset();setEmployeeId("")}}
  return <form className="access-separation" onSubmit={save}><strong>Завершить увольнение</strong><span>Действие отзовёт доступы. Выберите сотрудника и внесите документированное основание.</span><label><span>Сотрудник</span><SoftSelect name="employeeId" ariaLabel="Сотрудник для увольнения" value={employeeId} onChange={setEmployeeId} options={[{value:"",label:"Выберите сотрудника"},...employees.map(employee=>({value:employee.id,label:entityNames[employee.id]??recordLabel("Сотрудник",employee.id)}))]}/></label><label><span>Основание увольнения</span><textarea name="reason" required minLength={8} placeholder="Реквизиты заявления, приказа или соглашения"/></label><button className="danger" disabled={!employeeId||busy==="terminate-employee"}>{busy==="terminate-employee"?"Завершаем…":"Подтвердить увольнение и отозвать доступы"}</button></form>
}

function EmployeeModal({displayName,employee,profile,branches,busy,close,onOpenDocuments,submit}:{displayName:string;employee:Employee|null;profile:EmployeeProfile;branches:Branch[];busy:string;close:()=>void;onOpenDocuments:(focusId:string)=>void;submit:(body:Record<string,unknown>)=>Promise<void>}){
  const selectedIds=new Set(profile.branchIds?.length?profile.branchIds:branches.filter(branch=>employee?.unit.split(",").map(value=>value.trim()).includes(branch.name)).map(branch=>branch.id));
  function save(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget),branchIds=form.getAll("branchIds").map(String),branchNames=branches.filter(branch=>branchIds.includes(branch.id)).map(branch=>branch.name);void submit({...Object.fromEntries(form.entries()),branchIds,branchNames,unit:branchNames.join(", ")})}
  return createPortal(<div className="modal-layer staff-modal-layer"><button className="drawer-scrim" onClick={close} aria-label="Закрыть"/><form className="task-modal staff-modal" onSubmit={save}><div className="drawer-head"><div><p>Команда · единая карточка</p><h2>{employee?"Редактировать сотрудника":"Добавить сотрудника"}</h2></div><button type="button" onClick={close}>×</button></div><label><span>ФИО</span><input name="displayName" required defaultValue={displayName} placeholder="Имя и фамилия"/></label><div className="staff-form-grid"><label><span>Телефон или email</span><input name="contact" defaultValue={profile.contact??""} placeholder="+7… или name@arthello.ru"/><small>Этот контакт затем используется как логин при выдаче доступа.</small></label><fieldset className="staff-branch-picker"><legend>Филиалы сотрудника</legend>{branches.map(branch=><label key={branch.id}><input type="checkbox" name="branchIds" value={branch.id} defaultChecked={selectedIds.has(branch.id)}/><span>{branch.name}</span></label>)}</fieldset><label><span>Должность</span><input name="positionId" required defaultValue={employee?.positionId??""} placeholder="Учитель начальных классов"/></label><label><span>Тип занятости</span><SoftSelect name="employmentType" ariaLabel="Тип занятости" defaultValue={profile.employmentType??"Штат"} options={["Штат","Совместительство","ГПХ","Самозанятый"].map(value=>({value,label:value}))}/></label><label><span>Ставка, ₽</span><input type="number" min="0" name="rateRubles" defaultValue={employee?employee.rateMinor/100:0}/></label><label><span>Дата приёма</span><input type="date" name="hireDate" defaultValue={employee?.hireDate??new Date().toISOString().slice(0,10)}/></label><label><span>Статус</span><SoftSelect name="status" ariaLabel="Статус сотрудника" defaultValue={employee?.status??"Работает"} options={["Работает","На оформлении","Приостановлен"].map(value=>({value,label:value}))}/></label><label><span>Договор</span><span className="contract-field">{employee?.contractId?<><input readOnly value={recordLabel("Договор",employee.contractId)}/><input type="hidden" name="contractId" value={employee.contractId}/><button type="button" onClick={()=>onOpenDocuments(employee.contractId)}>Открыть в документах →</button></>:<input name="contractId" placeholder="Номер договора"/>}</span></label></div><label><span>Примечание</span><textarea name="note" defaultValue={profile.note??""} placeholder="Условия, специализация, важная информация"/></label><div className="access-separation"><strong>Доступ не создаётся автоматически</strong><span>Сотрудник появится в настройках пользователей с этим контактом и филиалами. При выдаче доступа филиальный контур можно только подтвердить или сузить.</span></div><div className="modal-actions"><button type="button" onClick={close}>Отмена</button><button disabled={busy==="save-employee"}>{busy==="save-employee"?"Сохраняем…":"Сохранить сотрудника"}</button></div></form></div>,document.body)
}

function ImportEmployeesModal({busy,close,submit}:{busy:string;close:()=>void;submit:(rows:Array<Record<string,unknown>>)=>Promise<void>}){
  const[raw,setRaw]=useState("ФИО;Контакт;Подразделение;Должность;Ставка;Дата приёма\n");
  const rows=useMemo(()=>parseRows(raw),[raw]);
  async function fileSelected(file?:File){if(file)setRaw(await file.text())}
  return createPortal(<div className="modal-layer staff-modal-layer"><button className="drawer-scrim" onClick={close} aria-label="Закрыть"/><section className="task-modal staff-modal import-staff-modal"><div className="drawer-head"><div><p>Контролируемый импорт</p><h2>Импорт персонала</h2></div><button onClick={close}>×</button></div><div className="import-rule"><strong>Никаких автоматических доступов</strong><span>Строки будут созданы со статусом «На проверке». Каждого сотрудника можно отредактировать до выдачи входа.</span></div><label className="file-drop"><span>CSV / TSV</span><input type="file" accept=".csv,.tsv,.txt,text/csv,text/tab-separated-values" onChange={event=>void fileSelected(event.target.files?.[0])}/><small>Можно сохранить таблицу как CSV или просто вставить строки из Excel ниже.</small></label><label><span>Предпросмотр данных</span><textarea value={raw} onChange={event=>setRaw(event.target.value)} rows={9}/></label><div className="import-preview"><strong>Готово к импорту: {rows.length}</strong><span>{rows.slice(0,3).map(row=>String(row.displayName)).join(" · ")||"Добавьте строки после заголовка"}</span></div><div className="modal-actions"><button onClick={close}>Отмена</button><button disabled={!rows.length||busy==="import-employees"} onClick={()=>void submit(rows)}>{busy==="import-employees"?"Импортируем…":"Импортировать на проверку"}</button></div></section></div>,document.body)
}

function parseRows(raw:string){const lines=raw.split(/\r?\n/).map(line=>line.trim()).filter(Boolean);if(!lines.length)return[];const first=lines[0].toLocaleLowerCase("ru");const start=first.includes("фио")||first.includes("имя")?1:0;return lines.slice(start).map(line=>{const cells=line.split(line.includes("\t")?"\t":";").map(cell=>cell.trim());return{displayName:cells[0],contact:cells[1]??"",unit:cells[2]??"",positionId:cells[3]??"",rateRubles:Number(String(cells[4]??"0").replace(/\s/g,"").replace(",","."))||0,hireDate:cells[5]??new Date().toISOString().slice(0,10),status:"Работает",employmentType:"Штат",contractId:"",note:""}}).filter(row=>row.displayName)}
function withBranchCatalog(row:Record<string,unknown>,branches:Branch[]){const requested=String(row.unit??"").split(/[,;|/]+/).map(value=>value.trim().toLocaleLowerCase("ru")).filter(Boolean),matched=branches.filter(branch=>requested.some(value=>branch.name.toLocaleLowerCase("ru")===value||branch.name.toLocaleLowerCase("ru").includes(value)));return{...row,branchIds:matched.map(branch=>branch.id),branchNames:matched.map(branch=>branch.name),unit:matched.map(branch=>branch.name).join(", ")||String(row.unit??"")}}
function humanHrEvidence(value:string){const references=value.replace(/\bINTV(?:-[A-Z0-9]+)+\b/gi,reference=>recordNumber(reference)).replace(/\bHR-DEC(?:-[A-Z0-9]+)+\b/gi,reference=>`кадровой службы ${recordNumber(reference)}`);return humanTechnicalText(references)}
function roleLabel(value:string){const labels:Record<string,string>={OWNER:"Собственник",DIRECTOR:"Директор",REPRESENTATIVE:"Представитель",HR:"Кадры",FINANCE:"Финансы",SALES:"Продажи",MARKETING:"Маркетинг",TEACHER:"Педагог",METHODIST:"Методист",PARENT:"Родитель"};return labels[value]??value}
function Head({p,h,s}:{p:string;h:string;s:string}){return <header className="hr-panel-head"><div><p>{p}</p><h2>{h}</h2></div><span>{s}</span></header>}
