import {
  pgTable,
  text,
  uuid,
  timestamp,
  numeric,
  integer,
  boolean,
  jsonb,
  uniqueIndex,
} from "drizzle-orm/pg-core";

// ─── Timeline Events ──────────────────────────────────────────────────────────
// Append-only immutable history of everything that happened to a family.
// Unique on (source_system, related_entity_type, related_entity_id) so
// build-timeline is safe to re-run.

export const timelineEventsTable = pgTable(
  "timeline_events",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    familyId: uuid("family_id"),
    personId: uuid("person_id"),
    studentPersonId: uuid("student_person_id"),
    eventType: text("event_type").notNull(),
    // event_type values:
    // lead_created | website_form | call_received |
    // whatsapp_message | telegram_message |
    // trial_lesson | lesson_attended | lesson_missed |
    // payment_received | payment_overdue |
    // subscription_started | subscription_ended |
    // churn_risk | manager_comment | manual_note | other
    eventTime: timestamp("event_time", { withTimezone: true }).notNull(),
    title: text("title"),
    description: text("description"),
    amount: numeric("amount"),
    sourceSystem: text("source_system"),
    relatedEntityType: text("related_entity_type"),
    relatedEntityId: text("related_entity_id"),
    severity: text("severity").default("info"), // info | warning | critical
    raw: jsonb("raw"),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  },
  (t) => ({
    uniqueSourceEntity: uniqueIndex("te_source_entity_idx").on(
      t.sourceSystem,
      t.relatedEntityType,
      t.relatedEntityId,
    ),
  }),
);

export type TimelineEvent = typeof timelineEventsTable.$inferSelect;

// ─── Family Health ────────────────────────────────────────────────────────────
// One row per family — overwritten each time calc-health runs.

export const familyHealthTable = pgTable("family_health", {
  id: uuid("id").primaryKey().defaultRandom(),
  familyId: uuid("family_id").unique().notNull(),
  healthScore: numeric("health_score").default("50"),
  paymentScore: numeric("payment_score").default("0"),
  attendanceScore: numeric("attendance_score").default("0"),
  engagementScore: numeric("engagement_score").default("0"),
  churnRiskScore: numeric("churn_risk_score").default("0.5"),
  lastPaymentAt: timestamp("last_payment_at", { withTimezone: true }),
  lastAttendanceAt: timestamp("last_attendance_at", { withTimezone: true }),
  missedLessons30d: integer("missed_lessons_30d").default(0),
  overdueAmount: numeric("overdue_amount").default("0"),
  activeStudents: integer("active_students").default(0),
  inactiveStudents: integer("inactive_students").default(0),
  calculatedAt: timestamp("calculated_at", { withTimezone: true }).defaultNow(),
});

export type FamilyHealth = typeof familyHealthTable.$inferSelect;

// ─── Health Alerts ────────────────────────────────────────────────────────────
// Generated by calc-health. Previous unresolved alerts are cleared on each run.

export const healthAlertsTable = pgTable("health_alerts", {
  id: uuid("id").primaryKey().defaultRandom(),
  familyId: uuid("family_id").notNull(),
  alertType: text("alert_type").notNull(),
  // overdue_payment | attendance_drop | inactive_family |
  // churn_risk | no_future_lessons | expiring_subscription
  severity: text("severity").notNull().default("warning"), // warning | critical
  message: text("message"),
  resolved: boolean("resolved").default(false),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
});

export type HealthAlert = typeof healthAlertsTable.$inferSelect;
