// Additive v52 SQLite/D1 runtime schema, generated from the paired migration.
export const developerFeedbackSchema = [
  "CREATE TABLE IF NOT EXISTS `developer_feedback` (\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`submission_id` text NOT NULL,\n\t`author_user_id` text NOT NULL,\n\t`author_name` text NOT NULL,\n\t`kind` text NOT NULL,\n\t`title` text NOT NULL,\n\t`body` text NOT NULL,\n\t`module_id` text DEFAULT '' NOT NULL,\n\t`status` text DEFAULT 'new' NOT NULL,\n\t`revision` integer DEFAULT 1 NOT NULL,\n\t`created_at` text NOT NULL,\n\t`updated_at` text NOT NULL,\n\tFOREIGN KEY (`author_user_id`) REFERENCES `app_users`(`id`) ON UPDATE no action ON DELETE restrict,\n\tCONSTRAINT \"developer_feedback_kind\" CHECK(\"developer_feedback\".\"kind\" IN ('bug','suggestion')),\n\tCONSTRAINT \"developer_feedback_title_length\" CHECK(length(\"developer_feedback\".\"title\") BETWEEN 1 AND 160),\n\tCONSTRAINT \"developer_feedback_body_length\" CHECK(length(\"developer_feedback\".\"body\") BETWEEN 1 AND 6000),\n\tCONSTRAINT \"developer_feedback_status\" CHECK(\"developer_feedback\".\"status\" IN ('new','reviewing','planned','done','declined')),\n\tCONSTRAINT \"developer_feedback_revision\" CHECK(\"developer_feedback\".\"revision\" >= 1)\n)",
  "CREATE UNIQUE INDEX IF NOT EXISTS `developer_feedback_author_submission` ON `developer_feedback` (`author_user_id`,`submission_id`)",
  "CREATE INDEX IF NOT EXISTS `developer_feedback_author_id` ON `developer_feedback` (`author_user_id`,`id`)",
  "CREATE TABLE IF NOT EXISTS `developer_feedback_events` (\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`feedback_id` integer NOT NULL,\n\t`revision` integer NOT NULL,\n\t`actor_user_id` text NOT NULL,\n\t`status` text NOT NULL,\n\t`created_at` text NOT NULL,\n\tFOREIGN KEY (`feedback_id`) REFERENCES `developer_feedback`(`id`) ON UPDATE no action ON DELETE restrict,\n\tFOREIGN KEY (`actor_user_id`) REFERENCES `app_users`(`id`) ON UPDATE no action ON DELETE restrict,\n\tCONSTRAINT \"developer_feedback_event_status\" CHECK(\"developer_feedback_events\".\"status\" IN ('new','reviewing','planned','done','declined'))\n)",
  "CREATE UNIQUE INDEX IF NOT EXISTS `developer_feedback_event_revision` ON `developer_feedback_events` (`feedback_id`,`revision`)"
] as const;

export const developerFeedbackColumns = {
  developer_feedback: ['id','submission_id','author_user_id','author_name','kind','title','body','module_id','status','revision','created_at','updated_at'],
  developer_feedback_events: ['id','feedback_id','revision','actor_user_id','status','created_at'],
} as const;
